
:experimental:
include::{partialsdir}/entities.adoc[]

[[sect-installation-complete-ppc]]
= Installation Complete

Congratulations! Your {PRODUCT} installation is now complete!

Click the btn:[Reboot] button to reboot your system and begin using {PRODUCT}. Remember to remove any installation media if it is not ejected automatically upon reboot.

After your computer's normal power-up sequence has completed,
{PRODUCT} loads and starts. By default,
the start process is hidden behind a graphical screen that displays
a progress bar. Eventually, a GUI login screen (or if the X Window
System is not installed, a `login:` prompt) appears.

If your system was installed with the X Window System during this installation process, the first time you start your {PRODUCT} system, applications to set up your system are launched. These applications guide you through initial configuration of {PRODUCT} and allow you to set your system time and date, and more.

See xref:InitialSetupHub-common.adoc#chap-initial-setup[Initial Setup] for information about the configuration process.
