
:experimental:
:toc:
include::{partialsdir}/entities.adoc[]

[[sect-consoles-logs-during-installation-x86]]
= Consoles and Logging During the Installation

The following sections describe how to access logs and an interactive shell during the installation. This is useful when troubleshooting problems, but should not be necessary in most cases.

[[sect-installation-consoles-x86]]
== Accessing Consoles

The {PRODUCT} installer uses the [application]*tmux* terminal multiplexer to display and control several windows you can use in addition to the main interface. Each of these windows serves a different purpose - they display several different logs, which can be used to troubleshoot any issues during the installation, and one of the windows provides an interactive shell prompt with `root` privileges, unless this prompt was specifically disabled using a boot option or a Kickstart command.

[NOTE]
====

In general, there is no reason to leave the default graphical installation environment unless you need to diagnose an installation problem.

====

The terminal multiplexer is running in virtual console 1. To switch from the graphical installation environment to [application]*tmux*, press kbd:[Ctrl + Alt + F1]. To go back to the main installation interface which runs in virtual console 6, press kbd:[Ctrl + Alt + F6].

[NOTE]
====

If you choose text mode installation, you will start in virtual console 1 ([application]*tmux*), and switching to console 6 will open a shell prompt instead of a graphical interface.

====

The console running [application]*tmux* has 5 available windows; their contents are described in the table below, along with keyboard shortcuts used to access them. Note that the keyboard shortcuts are two-part: first press kbd:[Ctrl + b], then release both keys, and press the number key for the window you want to use.

You can also use kbd:[Ctrl + b] kbd:[n] and kbd:[Ctrl + b] kbd:[p] to switch to the next or previous [application]*tmux* window, respectively.

[[tabl-tmux-windows-x86]]
.Available tmux Windows

[options="header"]
|===
|Shortcut|Contents
|kbd:[Ctrl + b] kbd:[1]|Main installation program window. Contains text-based prompts (during text mode installation or if you use VNC Direct Mode), and also some debugging information.
|kbd:[Ctrl + b] kbd:[2]|Interactive shell prompt with `root` privileges.
|kbd:[Ctrl + b] kbd:[3]|Installation log; displays messages stored in `/tmp/anaconda.log`.
|kbd:[Ctrl + b] kbd:[4]|Storage log; displays messages related storage devices from kernel and system services, stored in `/tmp/storage.log`.
|kbd:[Ctrl + b] kbd:[5]|Program log; displays messages from other system utilities, stored in `/tmp/program.log`.
|===

In addition to displaying diagnostic information in [application]*tmux* windows, [application]*Anaconda* also generates several log files, which can be transferred from the installation system. These log files are described in xref:Trouble-x86.adoc#tabl-installation-log-files-x86[Log Files Generated During the Installation (x86)], and directions for transferring them from the installation system are available in xref:Trouble-x86.adoc#chap-troubleshooting-x86[Troubleshooting Installation on AMD64 and Intel{nbsp}64 Systems].

[[sect-installation-screenshots-x86]]
== Saving Screenshots

You can press kbd:[Shift + Print Screen] at any time during the graphical installation to capture the current screen. These screenshots are saved to `/tmp/anaconda-screenshots/`.

Additionally, you can use the [command]`autostep --autoscreenshot` command in a Kickstart file to capture and save each step of the installation automatically. See xref:Kickstart2.adoc#sect-kickstart-commands[Kickstart Commands and Options] for details.
