:experimental:
:toc:
include::{partialsdir}/entities.adoc[]

[[appe-iscsi-disks]]
= iSCSI Disks

_Internet Small Computer System Interface_ (iSCSI) is a protocol that allows computers to communicate with storage devices by SCSI requests and responses carried over TCP/IP. Because iSCSI is based on the standard SCSI protocols, it uses some terminology from SCSI. The device on the SCSI bus to which requests get sent, and which answers these requests, is known as the _target_ and the device issuing requests is known as the _initiator_. In other words, an iSCSI disk is a target and the iSCSI software equivalent of a SCSI controller or SCSI Host Bus Adapter (HBA) is called an initiator. This appendix only covers Linux as an iSCSI initiator; how Linux uses iSCSI disks, but not how Linux hosts iSCSI disks.

Linux has a software iSCSI initiator in the kernel that takes the place and form of a SCSI HBA driver and therefore allows Linux to use iSCSI disks. However, as iSCSI is a fully network-based protocol, iSCSI initiator support requires more than just the ability to send SCSI packets over the network. Before Linux can use an iSCSI target, Linux must find the target on the network and make a connection to it. In some cases, Linux must send authentication information to gain access to the target. Linux must also detect any failure of the network connection and must establish a new connection, including logging in again if necessary.

The discovery, connection, and logging in is handled in user space by the [application]*iscsiadm* utility, while errors are handled, also in user space, by the [application]*iscsid* utility.

Both [application]*iscsiadm* and [application]*iscsid* are part of the [application]*iscsi-initiator-utils* package under {PRODUCT}.

[[sect-iscsi-disks-anaconda]]
== iSCSI Disks in Anaconda

The [application]*Anaconda* installation program can discover and log in to iSCSI disks in two ways:

. When [application]*Anaconda* starts, it checks if the BIOS or add-on boot ROMs of the system support _iSCSI Boot Firmware Table_ (iBFT), a BIOS extension for systems which can boot from iSCSI. If the BIOS supports iBFT, [application]*Anaconda* will read the iSCSI target information for the configured boot disk from the BIOS and log in to this target, making it available as an installation target.
+
[IMPORTANT]
====

To connect automatically to an iSCSI target, a network device for accessing the target needs to be activated. The recommended way to do so is to use [option]`ip=ibft` boot option.

====

. You can discover and add iSCSI targets manually in the graphical user interface in [application]*anaconda*. From the main menu, the Installation Summary screen, click the Installation Destination option. Then click the btn:[Add a disk] in the `Specialized & Network Disks` section of the screen. A tabbed list of available storage devices appears. In the lower right corner, click the btn:[Add iSCSI Target] button and proceed with the discovery process. See xref:FilterSpoke-x86.adoc#sect-storage-device-selection-x86[The Storage Devices Selection Screen (x86)] for more information.
+
The `/boot` partition cannot be placed on iSCSI targets which have been added manually using this method - an iSCSI target containing a `/boot` partition must be configured for use with iBFT.

While [application]*Anaconda* uses [application]*iscsiadm* to find and log into iSCSI targets, [application]*iscsiadm* automatically stores any information about these targets in the iscsiadm iSCSI database. [application]*Anaconda* then copies this database to the installed system and marks any iSCSI targets not used for `/` so that the system will automatically log in to them when it starts. If `/` is placed on an iSCSI target, [application]*initrd* will log into this target and [application]*Anaconda* does not include this target in start up scripts to avoid multiple attempts to log into the same target.

[[sect-iscsi-disks-startup]]
== iSCSI Disks During Start Up

Events related to iSCSI might occur at a number of points while the system is starting:

. The init script in the [application]*initrd* will log into iSCSI targets used for `/`, if any. This is done using the [application]*iscsistart* utility, without requiring [application]*iscsid* to run.
+
[NOTE]
====

If the root file system is on an iSCSI disk connected using IPv6, ensure that the installed system is using the correct [option]`ip=` boot option, for example [option]`ip=eth0:auto6`. If this option is not set, the installed system can spend up to 20 minutes at boot time attempting to establish a connection, before eventually succeeding. Using the correct [option]`ip=` option eliminates this delay.

====

. When the root file system has been mounted and the various service init scripts are running, the [application]*iscsi* init script will get called. This script then starts the [application]*iscsid* daemon if any iSCSI targets are used for `/`, or if any targets in the iSCSI database are marked to be logged into automatically.

. After the classic network service script has been run, the [application]*iscsi* init script will run. If the network is accessible, this will log into any targets in the iSCSI database that are marked to be logged into automatically. If the network is not accessible, this script will exit quietly.

. When using [application]*NetworkManager* to access the network, instead of the classic network service script, [application]*NetworkManager* will call the [application]*iscsi* init script. Also see the `/etc/NetworkManager/dispatcher.d/04-iscsi` file for further reference.
+
[IMPORTANT]
====

Because [application]*NetworkManager* is installed in the `/usr` directory, you cannot use it to configure network access if `/usr` is on network-attached storage such as an iSCSI target.

====

If [application]*iscsid* is not needed as the system starts, it will not start automatically. If you start [application]*iscsiadm*, [application]*iscsiadm* will start [application]*iscsid* in turn.
