
:experimental:
include::{partialsdir}/entities.adoc[]



[[sect-making-usb-media-macosx]]
= Making Installation USB Media on Mac OS X

This procedure involves using the [command]`dd` command line tool to write the installation image to a USB flash drive. Note that some steps involve use of the [command]`sudo` command, which is only available when logged in with an administrator account that requires a password.

[WARNING]
====

All data on the USB flash drive will be deleted by this procedure.

====

[[proc-making-usb-media-macosx]]
.Making USB Media on Mac OS X
. Connect a USB flash drive to the system and identify the device path with the [command]`diskutil list` command. The device path has the format of `/dev/diskpass:attributes[{blank}]_number_`, where _number_ is the number of the disk. The disks are numbered starting at zero (0). Disk 0 is likely to be the OS X recovery disk, and Disk 1 is likely to be your main OS X installation. In the following example, it is `disk2`:
+
[literal,subs="+quotes,verbatim"]
....
$ diskutil list
/dev/disk0
#:                       TYPE NAME                    SIZE       IDENTIFIER
0:      GUID_partition_scheme                        *500.3 GB   disk0
1:                        EFI EFI                     209.7 MB   disk0s1
2:          Apple_CoreStorage                         400.0 GB   disk0s2
3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
4:          Apple_CoreStorage                         98.8 GB    disk0s4
5:                 Apple_Boot Recovery HD             650.0 MB   disk0s5
/dev/disk1
#:                       TYPE NAME                    SIZE       IDENTIFIER
0:                  Apple_HFS YosemiteHD             *399.6 GB   disk1
Logical Volume on disk0s1
8A142795-8036-48DF-9FC5-84506DFBB7B2
Unlocked Encrypted
/dev/disk2
#:                       TYPE NAME                    SIZE       IDENTIFIER
0:     FDisk_partition_scheme                        *8.0 GB     disk2
1:               Windows_NTFS SanDisk USB             8.0 GB     disk2s1
....
+
To identify your USB flash drive, compare the `NAME`, `TYPE` and `SIZE` columns to what you know about your flash drive. For example, the `NAME` should be the same as the title of the flash drive icon in the [application]*Finder*. You can also compare these values to those in the flash drive's information panel; right-click on the drive icon and select `Get Info`.

. Use the [command]`diskutil unmountDisk` command to unmount the flash drive's filesystem volumes:
+
[literal,subs="+quotes,verbatim,macros"]
....
`$` [command]`diskutil unmountDisk /dev/diskpass:attributes[{blank}]_number_pass:attributes[{blank}]`
Unmount of all volumes on diskpass:attributes[{blank}]_number_ was successful
....
+
When you do this, the icon for the flash drive disappears from your desktop. If it does not, you might have identified the wrong disk. If you attempt to unmount the system disk accidentally, you get a `failed to unmount` error.

. Use the [command]`dd` command as a parameter of the [command]`sudo` command to write the ISO image to the flash drive:
+
[literal,subs="+quotes,verbatim,macros"]
....
$ [command]`sudo dd if=pass:attributes[{blank}]_/path/to/image.iso_ of=/dev/rdiskpass:attributes[{blank}]_number_ bs=1m>`
....
+
[NOTE]
====

Mac OS X provides both a block (`/dev/disk*`) and character device (`/dev/rdisk*`) file for each storage device. Writing an image to the `/dev/rdiskpass:attributes[{blank}]_number_pass:attributes[{blank}]` character device is faster than to the `/dev/diskpass:attributes[{blank}]_number_pass:attributes[{blank}]` block device.

====
+
.Writing an ISO Image to a Disk
====

To write the `/Users/pass:attributes[{blank}]_user_name_pass:attributes[{blank}]/Downloads/{PRODUCT}-server-x86_64-boot.iso` file to the `/dev/rdisk2` device:

[literal,subs="+quotes,attributes,verbatim"]
....
$ sudo dd if=/Users/user_name/Downloads/{PRODUCT}-server-x86_64-boot.iso of=/dev/rdisk2
....

====

. Wait for the command to finish. Note that no progress bar is displayed; however, to check the status of the operation while it is still running, press kbd:[Ctrl + t] in the terminal:
+
[literal,subs="+quotes,verbatim"]
....
load: 1.02  cmd: dd 3668 uninterruptible 0.00u 1.91s
112+0 records in
111+0 records out
116391936 bytes transferred in 114.834860 secs (1013559 bytes/sec)
....

. The speed of the data transfer depends on the speed of your USB ports and the flash drive. After the prompt is displayed again, the data transfer is finished. You can then unplug the flash drive.

The flash drive is now ready to be used as a boot device. You can continue with xref:Boot_x86.adoc#chap-booting-installer-x86[Booting the Installation on 64-bit AMD, Intel, and ARM systems] on AMD64 and Intel{nbsp}64 systems or xref:Boot_ppc.adoc#chap-booting-installer-ppc[Booting the Installation on IBM Power{nbsp}Systems] on IBM Power{nbsp}Systems servers.
