
:experimental:
include::{partialsdir}/entities.adoc[]

[[sect-making-media-additional-sources]]
= Preparing Installation Sources

As explained in xref:downloading.adoc#chap-download[Downloading {PRODUCT}], two basic types of media are available for {PRODUCT}: a minimal boot image and a full installation image (also known as a binary DVD). If you downloaded the binary DVD and created a boot DVD-ROM or USB drive from it, you can proceed with the installation immediately, as this image contains everything you need to install the system.

However, if you use the minimal boot image, you must also configure an additional source of the installation. This is because the minimal boot image only contains the installation program itself and tools needed to boot your system and start the installation; it does not include the software packages to be installed on your system.

The full installation DVD ISO image can be used as the source for the installation. If your system will require additional software not provided by Red{nbsp}Hat, you should configure additional repositories and install these packages _after_ the installation is finished. For information about configuring additional [application]*Yum* repositories on an installed system, see the link:++https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/index.html++[Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 System Administrator's Guide].

The installation source can be any of the following:

* `DVD`: You can burn the binary DVD ISO image onto a DVD and configure the installation program to install packages from this disk.

* `Hard drive`: You can place the binary DVD ISO image on a hard drive and install packages from it.

* `Network location`: You can copy the binary DVD ISO image or the _installation tree_ (extracted contents of the binary DVD ISO image) to a network location accessible from the installation system and perform the installation over the network using the following protocols:
+
** `NFS`: The binary DVD ISO image is placed into a _Network File System_ (NFS) share.
+
** `HTTPS`, `HTTP` or `FTP`: The installation tree is placed on a network location accessible over `HTTP`, `HTTPS`, or `FTP`.

When booting the installation from minimal boot media, you must always configure an additional installation source. When booting the installation from the full binary DVD, it is also possible to configure another installation source, but it is not necessary - the binary DVD ISO image itself contains all packages you need to install the system, and the installation program will automatically configure the binary DVD as the source.

You can specify an installation source in any of the following ways:

* In the installation program's graphical interface: After the graphical installation begins and you select your preferred language, the `Installation Summary` screen will appear. Navigate to the `Installation Source` screen and select the source you want to configure. For details, see:
+
** xref:SourceSpoke-x86.adoc#sect-installation-source-x86[Installation Source (x86)] for 64-bit AMD, Intel, and ARM systems
+
** xref:SourceSpoke-ppc64.adoc#sect-installation-source-ppc[Installation Source (ppc)] for IBM Power{nbsp}Systems servers

* Using a boot option: You can specify custom boot options to configure the installation program before it starts. One of these options allows you to specify the installation source to be used. See the [option]`inst.repo=` option in xref:adminoptions.adoc#sect-boot-options-installer[Configuring the Installation System at the Boot Menu] for details.

* Using a Kickstart file: You can use the [command]`install` command in a Kickstart file and specify an installation source. See xref:Kickstart2.adoc#sect-kickstart-commands[Kickstart Commands and Options] for details on the [command]`install` Kickstart command, and xref:Kickstart2.adoc#chap-kickstart-installations[Kickstart Installations] for information about Kickstart installations in general.
