site:
  title: CentOS Documentation
  start_page: centos:install-guide:index
content:
  sources:
   - url: .
     branches: HEAD
ui:
  bundle:
    url: ui-bundle.zip
    snapshot: true
  default_layout: with_menu
output:
  clean: true
  dir: ./public
  destinations:
  - provider: archive
runtime:
  pull: true
  cache_dir: ./cache
