
:experimental:
include::entities.adoc[]

[[sect-installation-complete-s390]]
=== Installation Complete

Congratulations! Your {PRODUCT} installation is now complete!

The installation program prompts you to prepare your system for reboot.

The installation program automatically reboots into the installed system.

Should the installation program not reboot, the installation program shows information from which device to do an IPL (boot). Accept the shutdown option and after shutdown, IPL from the DASD or SCSI LUN where the `/boot` partition for {PRODUCT} has been installed.

[[sect-installation-complete-ipl-zvm-s390]]
==== IPL under z/VM

To IPL from a DASD, for example using the DASD device 200 on the 3270 console, issue the command:

[literal,subs="+quotes,verbatim"]
....
#cp i 200
....

In DASD only environments where automatic partitioning (clearing data from all partitions) was used, the first activated DASD is where the `/boot` partition is typically located.

Using `/boot` on an FCP LUN, you must provide the WWPN and LUN for the FCP-attached device from which to IPL.

To IPL from an FCP-attached device:

. Provide FCP routing information to an FCP-attached device, for example, where `0x50050763050B073D` is the WWPN, and `0x4020400100000000` is the FCP LUN:
+
[literal,subs="+quotes,verbatim"]
....
#cp set loaddev portname 50050763 050B073D lun 40204001 00000000
....

. IPL the FCP adapter, for example `FC00`:
+
[literal,subs="+quotes,verbatim"]
....
#cp ipl FC00
....

[NOTE]
====

To disconnect from the 3270 terminal without stopping the Linux running in your virtual machine, use [command]`#cp disconnect` instead of [command]`#cp logoff`. When your virtual machine is re-connected using the usual logon procedure, it might be placed in CP console function mode (`CP READ`). If so, to resume execution on your virtual machine, enter the [command]`BEGIN` command.

====

[[sect-installation-complete-ipl-lpar-s390]]
==== IPL on an LPAR

For LPAR-based installations, on the HMC, issue a load command to the LPAR, specifying the particular DASD, or the FCP adapter, WWPN, and FCP LUN where the `/boot` partition is located.

[[sect-installation-complete-reipl-s390]]
==== Continuing after Reboot (re-IPL)

Following the automatic reboot or the manual IPL of the installed {PRODUCT} operating system, you can log on to the system through [application]*ssh*. Note that the only place from which you can log in as root is from the 3270 terminal or from other terminal devices listed in `/etc/securetty`.

The first time you start your {PRODUCT} system in a graphical environment, you can use [application]*Initial Setup* to guide you through {PRODUCT} configuration. [application]*Initial Setup* lets you configure your environment at the beginning, so that you can get started using your {PRODUCT} system quickly.

See <<chap-initial-setup>> for information about the configuration process.