
:experimental:
include::entities.adoc[]

[[chap-subscription-management-unregistering]]
== Unregistering from Red{nbsp}Hat Subscription Management Services

A system can only be registered with one subscription service. If you need to change which service your system is registered with or need to delete the registration in general, then the method to unregister depends on which type of subscription service the system was originally registered with.

[[sect-subscription-management-unregistering-rhsm]]
=== Systems Registered with Red{nbsp}Hat Subscription Management

Several different subscription services use the same, certificate-based framework to identify systems, installed products, and attached subscriptions. These services are Customer Portal Subscription Management (hosted), Subscription Asset Manager (on-premise subscription service), and CloudForms System Engine (on-premise subscription and content delivery services). These are all part of _Red{nbsp}Hat Subscription Management_.

For all services within Red{nbsp}Hat Subscription Management, the systems are managed with the Red{nbsp}Hat Subscription Manager client tools.

To unregister a system registered with a Red{nbsp}Hat Subscription Management server, use the [command]`unregister` command as `root` without any additional parameters:

[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] subscription-manager unregister
....

For additional information, see link:++https://access.redhat.com/site/documentation/en-US/Red_Hat_Subscription_Management/1/html/RHSM/index.html++[Using and Configuring Red{nbsp}Hat Subscription{nbsp}Manager].

[[sect-subscription-management-unregistering-satellite]]
=== Systems Registered with Red{nbsp}Hat Satellite

For a Satellite registration on the server, locate the system in the `Systems` tab and delete the appropriate profile.

For additional information, see link:++https://access.redhat.com/site/documentation/en-US/Red_Hat_Satellite/6.1/html/User_Guide/index.html++[Red{nbsp}Hat Satellite User Guide].