
:experimental:
include::entities.adoc[]

:doctype: book
include::Book_Info.adoc[]

include::getting-started.adoc[]

include::downloading.adoc[]

include::Making_Media.adoc[]

[[part-installation-intel-amd]]
= AMD64, Intel{nbsp}64, and ARM{nbsp}64 - Installation and Booting

This part of the [citetitle]_{PRODUCT} Installation Guide_ discusses the installation of {PRODUCT}{nbsp}7 on 64-bit AMD, Intel, and ARM systems as well as some basic troubleshooting. For advanced installation options, see <<part-advanced-installation-options>>.

include::Simple_Installation.adoc[]

include::Steps-x86.adoc[]

include::DU-Updating_drivers_during_installation_x86.adoc[]

include::Boot_x86.adoc[]

include::Graphical_Installation-x86.adoc[]

include::Trouble-x86.adoc[]

[[part-installation-ibm-power]]
= IBM Power{nbsp}Systems - Installation and Booting

This part of the [citetitle]_{PRODUCT} Installation Guide_ includes information about installation and basic post-installation troubleshooting for IBM Power{nbsp}Systems servers. IBM Power{nbsp}Systems servers include IBM PowerLinux servers and POWER7, POWER8, and POWER9 Power{nbsp}Systems servers running Linux. For advanced installation options, see <<part-advanced-installation-options>>.

[IMPORTANT]
====

Previous releases of {PRODUCT} supported 32-bit and 64-bit Power{nbsp}Systems servers (`ppc` and `ppc64`, respectively). {PRODUCT}{nbsp}7 supports only 64-bit Power{nbsp}Systems servers (`ppc64`).

====

include::Steps-ppc.adoc[]

include::DU-Updating_drivers_during_installation_ppc.adoc[]

include::Boot_ppc.adoc[]

include::Graphical_Installation-ppc.adoc[]

include::Trouble-ppc.adoc[]

[[part-advanced-installation-options]]
= Advanced Installation Options

This part of the [citetitle]_{PRODUCT} Installation Guide_ covers more advanced or uncommon methods of installing {PRODUCT}, including:

* customizing the installation program's behavior by specifying boot options

* setting up a PXE server to boot the installation program over a network

* installing with remote access through VNC

* using a Kickstart file to automate the installation process

* installing into a disk image instead of a physical drive

include::adminoptions.adoc[]

include::pxe-server.adoc[]

include::vnc-installations.adoc[]

include::headless-installations.adoc[]

include::Kickstart2.adoc[]

include::disk-image-install.adoc[]

[[part-after-installation]]
= After Installation

This part of the [citetitle]_{PRODUCT} Installation Guide_ covers finalizing the installation, as well as some installation tasks related to installation that you might perform at some time in the future. These include:

* performing common post-installation tasks

* using a {PRODUCT} installation disc to rescue a damaged system

* removing {PRODUCT} from your computer

include::InitialSetupHub-common.adoc[]

include::nextsteps.adoc[]

include::Rescue_Mode.adoc[]

include::uninstall.adoc[]

[[part-technical-appendixes]]
= Technical Appendixes

The appendixes in this section do not contain instructions on installing {PRODUCT}. Instead, they provide technical background that you might find helpful to understand the options that {PRODUCT} offers you at various points in the installation process.

include::Partitions-x86.adoc[]

include::iSCSI.adoc[]

include::Understanding_LVM.adoc[]

include::techref.adoc[]

include::ext4_to_xfs_command_reference_table.adoc[]

include::data_size_appendix.adoc[]

include::Revision_History.adoc[]
