
:experimental:
include::entities.adoc[]

[[chap-post-installation-configuration-s390]]
== Configuring an Installed Linux on IBM System{nbsp}z Instance

For more information about Linux on System{nbsp}z, see the publications listed in <<chap-additional-references-s390>>. Some of the most common tasks are described here.

[[sect-post-installation-adding-dasds-s390]]
=== Adding DASDs

DASDs (_Direct Access Storage Devices_) are a type of storage commonly used with IBM System{nbsp}z. Additional information about working with these storage devices can be found at the IBM Knowledge{nbsp}Center at link:++http://www-01.ibm.com/support/knowledgecenter/linuxonibm/com.ibm.linux.z.lgdd/lgdd_t_dasd_wrk.html++[].

The following is an example of how to set a DASD online, format it, and make the change persistent.

[NOTE]
====

Make sure the device is attached or linked to the Linux system if running under z/VM.

[literal,subs="+quotes,verbatim"]
....
CP ATTACH EB1C TO *
....

To link a mini disk to which you have access, issue, for example:

[literal,subs="+quotes,verbatim,macros"]
....
[command]`CP LINK RHEL7X 4B2E 4B2E MR`
[command]`DASD 4B2E LINKED R/W`
....

See [citetitle]_z/VM: CP Commands and Utilities Reference, SC24-6175_ for details about the commands.

====

[[sect-post-installation-adding-dasds-setting-online-s390]]
==== Dynamically Setting DASDs Online

To set a DASD online, follow these steps:

. Use the [command]`cio_ignore` utility to remove the DASD from the list of ignored devices and make it visible to Linux:
+
[literal,subs="+quotes,verbatim"]
....
# cio_ignore -r device_number
....
+
Replace _device_number_ with the device number of the DASD. For example:
+
[literal,subs="+quotes,verbatim"]
....
# cio_ignore -r 4b2e
....

. Set the device online. Use a command of the following form:
+
[literal,subs="+quotes,verbatim"]
....
# chccwdev -e device_number
....
+
Replace _device_number_ with the device number of the DASD. For example:
+
[literal,subs="+quotes,verbatim"]
....
# chccwdev -e 4b2e
....
+
As an alternative, you can set the device online using sysfs attributes:
+
.. Use the [command]`cd` command to change to the /sys/ directory that represents that volume:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cd /sys/bus/ccw/drivers/dasd-eckd/0.0.4b2e/
pass:quotes[`#`] ls -l
total 0
-r--r--r--  1 root root 4096 Aug 25 17:04 availability
-rw-r--r--  1 root root 4096 Aug 25 17:04 cmb_enable
-r--r--r--  1 root root 4096 Aug 25 17:04 cutype
-rw-r--r--  1 root root 4096 Aug 25 17:04 detach_state
-r--r--r--  1 root root 4096 Aug 25 17:04 devtype
-r--r--r--  1 root root 4096 Aug 25 17:04 discipline
-rw-r--r--  1 root root 4096 Aug 25 17:04 online
-rw-r--r--  1 root root 4096 Aug 25 17:04 readonly
-rw-r--r--  1 root root 4096 Aug 25 17:04 use_diag
....
+
.. Check to see if the device is already online:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cat online
0
....
+
.. If it is not online, enter the following command to bring it online:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo 1 > online
pass:quotes[`#`] cat online
1
....

. Verify which block devnode it is being accessed as:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ls -l
total 0
-r--r--r--  1 root root 4096 Aug 25 17:04 availability
lrwxrwxrwx  1 root root    0 Aug 25 17:07 block -> ../../../../block/dasdb
-rw-r--r--  1 root root 4096 Aug 25 17:04 cmb_enable
-r--r--r--  1 root root 4096 Aug 25 17:04 cutype
-rw-r--r--  1 root root 4096 Aug 25 17:04 detach_state
-r--r--r--  1 root root 4096 Aug 25 17:04 devtype
-r--r--r--  1 root root 4096 Aug 25 17:04 discipline
-rw-r--r--  1 root root    0 Aug 25 17:04 online
-rw-r--r--  1 root root 4096 Aug 25 17:04 readonly
-rw-r--r--  1 root root 4096 Aug 25 17:04 use_diag
....
+
As shown in this example, device 4B2E is being accessed as /dev/dasdb.

These instructions set a DASD online for the current session, but this is not persistent across reboots. For instructions on how to set a DASD online persistently, see <<sect-post-installation-dasds-setting-online-persistently-s390>>. When you work with DASDs, use the persistent device symbolic links under `/dev/disk/by-path/`. See the chapter about persistent storage device naming in the [citetitle]_link:++https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/persistent_naming.html++[Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 Storage Administration Guide]_ for more in-depth information about different ways to consistently refer to storage devices.

[[sect-post-installation-preparing-dasds-s390]]
==== Preparing a New DASD with Low-level Formatting

Once the disk is online, change back to the `/root` directory and low-level format the device. This is only required once for a DASD during its entire lifetime:

[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cd /root
pass:quotes[`#`] dasdfmt -b 4096 -d cdl -p /dev/disk/by-path/ccw-0.0.4b2e
Drive Geometry: 10017 Cylinders * 15 Heads =  150255 Tracks

I am going to format the device /dev/disk/by-path/ccw-0.0.4b2e in the following way:
Device number of device : 0x4b2e
Labelling device        : yes
Disk label              : VOL1
Disk identifier         : 0X4B2E
Extent start (trk no)   : 0
Extent end (trk no)     : 150254
Compatible Disk Layout  : yes
Blocksize               : 4096

--->> ATTENTION! <<---
All data of that device will be lost.
Type "yes" to continue, no will leave the disk untouched: yes
cyl    97 of  3338 |#----------------------------------------------|   2%
....

When the progress bar reaches the end and the format is complete, [application]*dasdfmt* prints the following output:

[literal,subs="+quotes,verbatim"]
....
Rereading the partition table...
Exiting...
....

Now, use fdasd to partition the DASD. You can create up to three partitions on a DASD. In our example here, we create one partition spanning the whole disk:

[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] fdasd -a /dev/disk/by-path/ccw-0.0.4b2e
auto-creating one partition for the whole disk...
writing volume label...
writing VTOC...
checking !
wrote NATIVE!
rereading partition table...
....

After a (low-level formatted) DASD is online, it can be used like any other disk under Linux. For instance, you can create file systems, LVM physical volumes, or swap space on its partitions, for example `/dev/disk/by-path/ccw-0.0.4b2e-part1`. Never use the full DASD device (`dev/dasdb`) for anything but the commands [command]`dasdfmt` and [command]`fdasd`. If you want to use the entire DASD, create one partition spanning the entire drive as in the `fdasd` example above.

To add additional disks later without breaking existing disk entries in, for example, `/etc/fstab`, use the persistent device symbolic links under `/dev/disk/by-path/`.

[[sect-post-installation-dasds-setting-online-persistently-s390]]
==== Persistently Setting DASDs Online

The above instructions described how to activate DASDs dynamically in a running system. However, such changes are not persistent and do not survive a reboot. Making changes to the DASD configuration persistent in your Linux system depends on whether the DASDs belong to the root file system. Those DASDs required for the root file system need to be activated very early during the boot process by the `initramfs` to be able to mount the root file system.

The [command]`cio_ignore` commands are handled transparently for persistent device configurations and you do not need to free devices from the ignore list manually.

[[sect-post-installation-dasds-on-root-s390]]
===== DASDs That Are Part of the Root File System

The only file you have to modify to add DASDs that are part of the root file system is `/etc/zipl.conf`. Then run the [application]*zipl* boot loader tool. There is no need to recreate the `initramfs`.

There is one boot option to activate DASDs early in the boot process: `rd.dasd=`. This option takes a comma-separated list as input. The list contains a device bus ID and optional additional parameters consisting of key-value pairs that correspond to DASD [application]*sysfs* attributes.

Below is an example `zipl.conf` for a system that uses physical volumes on partitions of two DASDs for an LVM volume group `vg_devel1` that contains a logical volume `lv_root` for the root file system.

[literal,subs="+quotes,verbatim"]
....
[defaultboot]
default=linux
target=/boot/

[linux]
image=/boot/vmlinuz-2.6.32-19.el7.s390x
ramdisk=/boot/initramfs-2.6.32-19.el7.s390x.img
parameters="root=/dev/mapper/vg_devel1-lv_root rd.dasd=0.0.0200,use_diag=0,readonly=0,erplog=0,failfast=0 rd.dasd=0.0.0207,use_diag=0,readonly=0,erplog=0,failfast=0  rd_LVM_LV=vg_devel1/lv_root rd_NO_LUKS rd_NO_MD rd_NO_DM LANG=en_US.UTF-8 SYSFONT=latarcyrheb-sun16 KEYTABLE=us cio_ignore=all,!condev"
....

Suppose that you want to add another physical volume on a partition of a third DASD with device bus ID `0.0.202b`. To do this, add `rd.dasd=0.0.202b` to the parameters line of your boot kernel in `zipl.conf`:

[literal,subs="+quotes,verbatim"]
....
[defaultboot]
default=linux
target=/boot/

[linux]
image=/boot/vmlinuz-2.6.32-19.el7.s390x
ramdisk=/boot/initramfs-2.6.32-19.el7.s390x.img
parameters="root=/dev/mapper/vg_devel1-lv_root rd.dasd=0.0.0200,use_diag=0,readonly=0,erplog=0,failfast=0 rd.dasd=0.0.0207,use_diag=0,readonly=0,erplog=0,failfast=0 rd.dasd=0.0.202b  rd_LVM_LV=vg_devel1/lv_root rd_NO_LUKS rd_NO_MD rd_NO_DM LANG=en_US.UTF-8 SYSFONT=latarcyrheb-sun16 KEYTABLE=us cio_ignore=all,!condev"

....

[WARNING]
====

Make sure the length of the kernel command line in `/etc/zipl.conf` does not exceed 896 bytes. Otherwise, the boot loader cannot be saved, and the installation fails.

====

Run [command]`zipl` to apply the changes of `/etc/zipl.conf` for the next IPL:

[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] zipl -V
Using config file '/etc/zipl.conf'
Target device information
Device..........................: 5e:00
Partition.......................: 5e:01
Device name.....................: dasda
DASD device number..............: 0201
Type............................: disk partition
Disk layout.....................: ECKD/compatible disk layout
Geometry - heads................: 15
Geometry - sectors..............: 12
Geometry - cylinders............: 3308
Geometry - start................: 24
File system block size..........: 4096
Physical block size.............: 4096
Device size in physical blocks..: 595416
Building bootmap in '/boot/'
Building menu 'rh-automatic-menu'
Adding #1: IPL section 'linux' (default)
kernel image......: /boot/vmlinuz-2.6.32-19.el7.s390x
kernel parmline...: 'root=/dev/mapper/vg_devel1-lv_root rd.dasd=0.0.0200,use_diag=0,readonly=0,erplog=0,failfast=0 rd.dasd=0.0.0207,use_diag=0,readonly=0,erplog=0,failfast=0 rd.dasd=0.0.202b rd_LVM_LV=vg_devel1/lv_root rd_NO_LUKS rd_NO_MD rd_NO_DM LANG=en_US.UTF-8 SYSFONT=latarcyrheb-sun16 KEYTABLE=us cio_ignore=all,!condev'
initial ramdisk...: /boot/initramfs-2.6.32-19.el7.s390x.img
component address:
kernel image....: 0x00010000-0x00a70fff
parmline........: 0x00001000-0x00001fff
initial ramdisk.: 0x02000000-0x022d2fff
internal loader.: 0x0000a000-0x0000afff
Preparing boot device: dasda (0201).
Preparing boot menu
Interactive prompt......: enabled
Menu timeout............: 15 seconds
Default configuration...: 'linux'
Syncing disks...
Done.
....

[[sect-post-installation-dasds-no-root-s390]]
===== DASDs That Are Not Part of the Root File System

DASDs that are not part of the root file system, that is, _data disks_, are persistently configured in the file `/etc/dasd.conf`. It contains one DASD per line. Each line begins with the device bus ID of a DASD. Optionally, each line can continue with options separated by space or tab characters. Options consist of key-value-pairs, where the key and value are separated by an equals sign.

The key corresponds to any valid `sysfs` attribute a DASD can have. The value will be written to the key's `sysfs` attribute. Entries in `/etc/dasd.conf` are activated and configured by udev when a DASD is added to the system. At boot time, all DASDs visible to the system get added and trigger [application]*udev*.

Example content of `/etc/dasd.conf`:

[literal,subs="+quotes,verbatim"]
....
0.0.0207
0.0.0200 use_diag=1 readonly=1
....

Modifications of `/etc/dasd.conf` only become effective after a reboot of the system or after the dynamic addition of a new DASD by changing the system's I/O configuration (that is, the DASD is attached under z/VM). Alternatively, you can trigger the activation of a new entry in `/etc/dasd.conf` for a DASD which was previously not active, by executing the following commands:

. Use the [command]`cio_ignore` utility to remove the DASD from the list of ignored devices and make it visible to Linux:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r device_number
....
+
For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r 021a
....

. Trigger the activation by writing to the `uevent` attribute of the device:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo add > /sys/bus/ccw/devices/device-bus-ID/uevent
....
+
For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo add > /sys/bus/ccw/devices/0.0.021a/uevent
....

[[sect-post-installation-fcp-attached-luns-s390]]
=== Adding FCP-attached Logical Units (LUNs)

The following is an example of how to add an FCP LUN.

[NOTE]
====

If running under z/VM, make sure the FCP adapter is attached to the z/VM guest virtual machine. For multipathing in production environments there would be at least two FCP devices on two different physical adapters (CHPIDs). For example:

[literal,subs="+quotes,verbatim"]
....
CP ATTACH FC00 TO *
CP ATTACH FCD0 TO *
....

====

[[sect-post-installation-fcp-attached-luns-dynamic-s390]]
==== Dynamically Activating an FCP LUN

Follow these steps to activate a LUN:

. Use the [command]`cio_ignore` utility to remove the FCP adapter from the list of ignored devices and make it visible to Linux:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r device_number
....
+
Replace _device_number_ with the device number of the FCP adapter. For example:

. To bring the FCP adapter device online, use the following command:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] chccwdev -e fc00
....

. Verify that the required WWPN was found by the automatic port scanning of the zfcp device driver:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ls -l /sys/bus/ccw/drivers/zfcp/0.0.fc00/
drwxr-xr-x.  3 root root    0 Apr 28 18:19 0x500507630040710b
drwxr-xr-x.  3 root root    0 Apr 28 18:19 0x50050763050b073d
drwxr-xr-x.  3 root root    0 Apr 28 18:19 0x500507630e060521
drwxr-xr-x.  3 root root    0 Apr 28 18:19 0x500507630e860521
-r--r--r--.  1 root root 4096 Apr 28 18:17 availability
-r--r--r--.  1 root root 4096 Apr 28 18:19 card_version
-rw-r--r--.  1 root root 4096 Apr 28 18:17 cmb_enable
-r--r--r--.  1 root root 4096 Apr 28 18:17 cutype
-r--r--r--.  1 root root 4096 Apr 28 18:17 devtype
lrwxrwxrwx.  1 root root    0 Apr 28 18:17 driver ->  ../../../../bus/ccw/drivers/zfcp
-rw-r--r--.  1 root root 4096 Apr 28 18:17 failed
-r--r--r--.  1 root root 4096 Apr 28 18:19 hardware_version
drwxr-xr-x. 35 root root    0 Apr 28 18:17 host0
-r--r--r--.  1 root root 4096 Apr 28 18:17 in_recovery
-r--r--r--.  1 root root 4096 Apr 28 18:19 lic_version
-r--r--r--.  1 root root 4096 Apr 28 18:17 modalias
-rw-r--r--.  1 root root 4096 Apr 28 18:17 online
-r--r--r--.  1 root root 4096 Apr 28 18:19 peer_d_id
-r--r--r--.  1 root root 4096 Apr 28 18:19 peer_wwnn
-r--r--r--.  1 root root 4096 Apr 28 18:19 peer_wwpn
--w-------.  1 root root 4096 Apr 28 18:19 port_remove
--w-------.  1 root root 4096 Apr 28 18:19 port_rescan
drwxr-xr-x.  2 root root    0 Apr 28 18:19 power
-r--r--r--.  1 root root 4096 Apr 28 18:19 status
lrwxrwxrwx.  1 root root    0 Apr 28 18:17 subsystem ->  ../../../../bus/ccw
-rw-r--r--.  1 root root 4096 Apr 28 18:17 uevent
....

. Activate the FCP LUN by adding it to the port (WWPN) through which you would like to access the LUN:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo 0x4020400100000000 > /sys/bus/ccw/drivers/zfcp/0.0.fc00/0x50050763050b073d/unit_add
....

. Find out the assigned SCSI device name:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] lszfcp -DV
/sys/devices/css0/0.0.0015/0.0.fc00/0x50050763050b073d/0x4020400100000000
/sys/bus/ccw/drivers/zfcp/0.0.fc00/host0/rport-0:0-21/target0:0:21/0:0:21:1089355792
....

[[sect-post-installation-fcp-attached-luns-persistent-s390]]
==== Persistently activating FCP LUNs

The above instructions described how to activate FCP LUNs dynamically in a running system. However, such changes are not persistent and do not survive a reboot. How you make the changes to the FCP configuration persistent in your Linux system depends on whether the FCP LUNs belong to the root file system. Those required for the root file system need to be activated very early during the boot process by the `initramfs` to be able to mount the root file system. The [command]`cio_ignore` commands are handled transparently for persistent device configurations and you do not need to free devices from the ignore list manually.

[[sect-post-installation-fcp-attached-luns-on-root-s390]]
===== FCP LUNs That Are Part of the Root File System

The only file you have to modify for adding FCP LUNs that are part of the root file system is `/etc/zipl.conf` followed by a run of the [application]*zipl* boot loader tool. There is no more need to recreate the `initramfs`.

{PRODUCT} provides a parameter to activate FCP LUNs early in the boot process: `rd.zfcp=`. The value is a comma-separated list containing the device bus ID, the WWPN as 16 digit hexadecimal number prefixed with `0x`, and the FCP LUN prefixed with `0x` and padded with zeroes to the right to have 16 hexadecimal digits.

The following example `zipl.conf` is for a system that uses physical volumes on partitions of two FCP LUNs for an LVM volume group `vg_devel1` that contains a logical volume `lv_root` for the root file system. For simplicity, the example shows a configuration without multipathing.

[literal,subs="+quotes,verbatim"]
....
[defaultboot]
default=linux
target=/boot/

[linux]
image=/boot/vmlinuz-2.6.32-19.el7.s390x
ramdisk=/boot/initramfs-2.6.32-19.el7.s390x.img
parameters="root=/dev/mapper/vg_devel1-lv_root
rd.zfcp=0.0.fc00,0x5105074308c212e9,0x401040a000000000
rd.zfcp=0.0.fc00,0x5105074308c212e9,0x401040a100000000
rd_LVM_LV=vg_devel1/lv_root rd_NO_LUKS rd_NO_MD rd_NO_DM LANG=en_US.UTF-8
SYSFONT=latarcyrheb-sun16 KEYTABLE=us cio_ignore=all,!condev"
....

To add another physical volume on a partition of a third FCP LUN with device bus ID 0.0.fc00, WWPN 0x5105074308c212e9 and FCP LUN 0x401040a300000000, add `rd.zfcp=0.0.fc00,0x5105074308c212e9,0x401040a300000000` to the parameters line of your boot kernel in `zipl.conf`. For example:

[literal,subs="+quotes,verbatim,macros"]
....
[defaultboot]
default=linux
target=/boot/

[linux]
image=/boot/vmlinuz-2.6.32-19.el7.s390x
ramdisk=/boot/initramfs-2.6.32-19.el7.s390x.img
parameters="root=/dev/mapper/vg_devel1-lv_root
rd.zfcp=0.0.fc00,0x5105074308c212e9,0x401040a000000000
rd.zfcp=0.0.fc00,0x5105074308c212e9,0x401040a100000000
pass:quotes[_rd.zfcp=0.0.fc00,0x5105074308c212e9,0x401040a300000000_]
rd_LVM_LV=vg_devel1/lv_root rd_NO_LUKS rd_NO_MD rd_NO_DM LANG=en_US.UTF-8
SYSFONT=latarcyrheb-sun16 KEYTABLE=us cio_ignore=all,!condev"
....

[WARNING]
====

Make sure the length of the kernel command line in `/etc/zipl.conf` does not exceed 896 bytes. Otherwise, the boot loader cannot be saved, and the installation fails.

====

Run [application]*zipl* to apply the changes of `/etc/zipl.conf` for the next IPL:

[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] zipl -V
Using config file '/etc/zipl.conf'
Target device information
Device..........................: 08:00
Partition.......................: 08:01
Device name.....................: sda
Device driver name..............: sd
Type............................: disk partition
Disk layout.....................: SCSI disk layout
Geometry - start................: 2048
File system block size..........: 4096
Physical block size.............: 512
Device size in physical blocks..: 10074112
Building bootmap in '/boot/'
Building menu 'rh-automatic-menu'
Adding #1: IPL section 'linux' (default)
kernel image......: /boot/vmlinuz-2.6.32-19.el7.s390x
kernel parmline...: 'root=/dev/mapper/vg_devel1-lv_root rd.zfcp=0.0.fc00,0x5105074308c212e9,0x401040a000000000 rd.zfcp=0.0.fc00,0x5105074308c212e9,0x401040a100000000 rd.zfcp=0.0.fc00,0x5105074308c212e9,0x401040a300000000 rd_LVM_LV=vg_devel1/lv_root rd_NO_LUKS rd_NO_MD rd_NO_DM LANG=en_US.UTF-8 SYSFONT=latarcyrheb-sun16 KEYTABLE=us cio_ignore=all,!condev'
initial ramdisk...: /boot/initramfs-2.6.32-19.el7.s390x.img
component address:
kernel image....: 0x00010000-0x007a21ff
parmline........: 0x00001000-0x000011ff
initial ramdisk.: 0x02000000-0x028f63ff
internal loader.: 0x0000a000-0x0000a3ff
Preparing boot device: sda.
Detected SCSI PCBIOS disk layout.
Writing SCSI master boot record.
Syncing disks...
Done.
....

[[sect-post-installation-fcp-attached-luns-no-root-s390]]
===== FCP LUNs That Are Not Part of the Root File System

FCP LUNs that are not part of the root file system, such as data disks, are persistently configured in the file `/etc/zfcp.conf`. It contains one FCP LUN per line. Each line contains the device bus ID of the FCP adapter, the WWPN as 16 digit hexadecimal number prefixed with `0x`, and the FCP LUN prefixed with `0x` and padded with zeroes to the right to have 16 hexadecimal digits, separated by a space or tab. Entries in `/etc/zfcp.conf` are activated and configured by udev when an FCP adapter is added to the system. At boot time, all FCP adapters visible to the system are added and trigger [application]*udev*.

Example content of `/etc/zfcp.conf`:

[literal,subs="+quotes,verbatim"]
....
0.0.fc00 0x5105074308c212e9 0x401040a000000000
0.0.fc00 0x5105074308c212e9 0x401040a100000000
0.0.fc00 0x5105074308c212e9 0x401040a300000000
0.0.fcd0 0x5105074308c2aee9 0x401040a000000000
0.0.fcd0 0x5105074308c2aee9 0x401040a100000000
0.0.fcd0 0x5105074308c2aee9 0x401040a300000000
....

Modifications of `/etc/zfcp.conf` only become effective after a reboot of the system or after the dynamic addition of a new FCP channel by changing the system's I/O configuration (for example, a channel is attached under z/VM). Alternatively, you can trigger the activation of a new entry in `/etc/zfcp.conf` for an FCP adapter which was previously not active, by executing the following commands:

. Use the [command]`cio_ignore` utility to remove the FCP adapter from the list of ignored devices and make it visible to Linux:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r device_number
....
+
Replace _device_number_ with the device number of the FCP adapter. For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r fcfc
....

. To trigger the uevent that activates the change, issue:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo add > /sys/bus/ccw/devices/device-bus-ID/uevent
....
+
For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo add > /sys/bus/ccw/devices/0.0.fcfc/uevent
....

[[sect-post-installation-adding-network-devices-s390]]
=== Adding a Network Device

Network device driver modules are loaded automatically by [application]*udev*.

You can add a network interface on IBM System{nbsp}z dynamically or persistently.

* Dynamically
+
.. Load the device driver
+
.. Remove the network devices from the list of ignored devices.
+
.. Create the group device.
+
.. Configure the device.
+
.. Set the device online.

* Persistently
+
.. Create a configuration script.
+
.. Activate the interface.

The following sections provide basic information for each task of each IBM System{nbsp}z network device driver. <<sect-post-installation-qeth-device-s390>> describes how to add a qeth device to an existing instance of {PRODUCT}. <<sect-post-installation-lcs-s390>> describes how to add an lcs device to an existing instance of {PRODUCT}.

[[sect-post-installation-qeth-device-s390]]
==== Adding a qeth Device

The `qeth` network device driver supports System{nbsp}z OSA-Express features in QDIO mode, HiperSockets, z/VM guest LAN, and z/VM VSWITCH.

The `qeth` device driver assigns the same interface name for Ethernet and Hipersockets devices: `enccw`pass:attributes[{blank}]pass:attributes[{blank}]_bus_ID_. The bus ID is composed of the channel subsystem ID, subchannel set ID, and device number, for example `enccw0.0.0a00`.

[[sect-post-installation-qeth-device-dynamic-s390]]
===== Dynamically Adding a qeth Device

To add a `qeth` device dynamically, follow these steps:

. Determine whether the `qeth` device driver modules are loaded. The following example shows loaded `qeth` modules:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] lsmod | grep qeth
											qeth_l3                  127056  9
											qeth_l2                   73008  3
											ipv6                  492872  155ip6t_REJECT,nf_conntrack_ipv6,qeth_l3
											qeth                  115808  2 qeth_l3,qeth_l2
											qdio                   68240  1 qeth
											ccwgroup               12112  2 qeth
....
+
If the output of the [command]`lsmod` command shows that the `qeth` modules are not loaded, run the [command]`modprobe` command to load them:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] modprobe qeth
....

. Use the [command]`cio_ignore` utility to remove the network channels from the list of ignored devices and make them visible to Linux:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r read_device_bus_id,write_device_bus_id,data_device_bus_id
....
+
Replace _read_device_bus_id_,_write_device_bus_id_,_data_device_bus_id_ with the three device bus IDs representing a network device. For example, if the _read_device_bus_id_ is `0.0.f500`, the _write_device_bus_id_ is `0.0.f501`, and the _data_device_bus_id_ is `0.0.f502`:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r 0.0.f500,0.0.f501,0.0.f502
....

. Use the [application]*znetconf* utility to sense and list candidate configurations for network devices:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] znetconf -u
Scanning for network devices...
Device IDs                 Type    Card Type      CHPID Drv.
------------------------------------------------------------
0.0.f500,0.0.f501,0.0.f502 1731/01 OSA (QDIO)        00 qeth
0.0.f503,0.0.f504,0.0.f505 1731/01 OSA (QDIO)        01 qeth
0.0.0400,0.0.0401,0.0.0402 1731/05 HiperSockets      02 qeth
....

. Select the configuration you want to work with and use [application]*znetconf* to apply the configuration and to bring the configured group device online as network device.
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] znetconf -a f500
Scanning for network devices...
Successfully configured device 0.0.f500 (enccw0.0.f500)
....

. Optionally, you can also pass arguments that are configured on the group device before it is set online:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] znetconf -a f500 -o portname=myname
Scanning for network devices...
Successfully configured device 0.0.f500 (enccw0.0.f500)
....
+
Now you can continue to configure the `enccw0.0.f500` network interface.

Alternatively, you can use `sysfs` attributes to set the device online as follows:

. Create a `qeth` group device:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo read_device_bus_id,write_device_bus_id,data_device_bus_id > /sys/bus/ccwgroup/drivers/qeth/group
....
+
For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo 0.0.f500,0.0.f501,0.0.f502 > /sys/bus/ccwgroup/drivers/qeth/group
....

. Next, verify that the `qeth` group device was created properly by looking for the read channel:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ls /sys/bus/ccwgroup/drivers/qeth/0.0.f500
....
+
You can optionally set additional parameters and features, depending on the way you are setting up your system and the features you require, such as:
+
** `portno`
+
** `layer2`
+
** `portname`

. Bring the device online by writing `1` to the online `sysfs` attribute:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo 1 > /sys/bus/ccwgroup/drivers/qeth/0.0.f500/online
....

. Then verify the state of the device:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cat /sys/bus/ccwgroup/drivers/qeth/0.0.f500/online
											1
....
+
A return value of `1` indicates that the device is online, while a return value `0` indicates that the device is offline.

. Find the interface name that was assigned to the device:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cat /sys/bus/ccwgroup/drivers/qeth/0.0.f500/if_name
enccw0.0.f500
....
+
Now you can continue to configure the `enccw0.0.f500` network interface.
+
The following command from the [package]*s390utils* package shows the most important settings of your `qeth` device:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] lsqeth enccw0.0.f500
Device name                     : enccw0.0.f500
-------------------------------------------------
card_type               : OSD_1000
cdev0                   : 0.0.f500
cdev1                   : 0.0.f501
cdev2                   : 0.0.f502
chpid                   : 76
online                  : 1
portname                : OSAPORT
portno                  : 0
state                   : UP (LAN ONLINE)
priority_queueing       : always queue 0
buffer_count            : 16
layer2                  : 1
isolation               : none
....

[[sect-post-installation-qeth-device-dynamic-remove-s390]]
===== Dynamically Removing a qeth Device

To remove a `qeth` device, use the [application]*znetconf* utility. For example:

. Use the [command]`znetconf` utility to show you all configured network devices:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] znetconf -c
Device IDs                 Type    Card Type      CHPID Drv. Name        	State
--------------------------------------------------------------------------------------
0.0.8036,0.0.8037,0.0.8038 1731/05 HiperSockets      FB qeth hsi1        	online
0.0.f5f0,0.0.f5f1,0.0.f5f2 1731/01 OSD_1000          76 qeth enccw0.0.09a0      online
0.0.f500,0.0.f501,0.0.f502 1731/01 GuestLAN QDIO     00 qeth enccw0.0.f500      online
....

. Select the network device to be removed and run [command]`znetconf` to set the device offline and ungroup the `ccw`pass:attributes[{blank}]> group device.
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] znetconf -r f500
Remove network device 0.0.f500 (0.0.f500,0.0.f501,0.0.f502)?
Warning: this may affect network connectivity!
Do you want to continue (y/n)?y
Successfully removed device 0.0.f500 (enccw0.0.f500)
....

. Verify the success of the removal:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] znetconf -c
Device IDs                 Type    Card Type      CHPID Drv. Name        	State
--------------------------------------------------------------------------------------
0.0.8036,0.0.8037,0.0.8038 1731/05 HiperSockets      FB qeth hsi1        	online
0.0.f5f0,0.0.f5f1,0.0.f5f2 1731/01 OSD_1000          76 qeth enccw0.0.09a0      online
....

[[sect-post-installation-qeth-device-persistent-s390]]
===== Persistently Adding a qeth Device

To make your new `qeth` device persistent, you need to create the configuration file for your new interface. The network interface configuration files are placed in the `/etc/sysconfig/network-scripts/` directory.

The network configuration files use the naming convention `ifcfg-_device_pass:attributes[{blank}]`, where _device_ is the value found in the `if_name` file in the `qeth` group device that was created earlier, for example `enccw0.0.09a0`. The [command]`cio_ignore` commands are handled transparently for persistent device configurations and you do not need to free devices from the ignore list manually.

If a configuration file for another device of the same type already exists, the simplest way is to copy it to the new name and then edit it:

[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cd /etc/sysconfig/network-scripts
pass:quotes[`#`] cp ifcfg-enccw0.0.09a0 ifcfg-enccw0.0.0600
....

To learn IDs of your network devices, use the [application]*lsqeth* utility:

[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] lsqeth -p
devices                    CHPID interface        cardtype       port chksum prio-q'ing rtr4 rtr6 lay'2 cnt
-------------------------- ----- ---------------- -------------- ---- ------ ---------- ---- ---- ----- -----
0.0.09a0/0.0.09a1/0.0.09a2 x00   enccw0.0.09a0    Virt.NIC QDIO  0    sw     always_q_2 n/a  n/a  1     64
0.0.0600/0.0.0601/0.0.0602 x00   enccw0.0.0600    Virt.NIC QDIO  0    sw     always_q_2 n/a  n/a  1     64
....

If you do not have a similar device defined, you must create a new file. Use this example of `/etc/sysconfig/network-scripts/ifcfg-0.0.09a0` as a template:

[literal,subs="+quotes,verbatim"]
....
# IBM QETH
DEVICE=enccw0.0.09a0
BOOTPROTO=static
IPADDR=10.12.20.136
NETMASK=255.255.255.0
ONBOOT=yes
NETTYPE=qeth
SUBCHANNELS=0.0.09a0,0.0.09a1,0.0.09a2
PORTNAME=OSAPORT
OPTIONS='layer2=1 portno=0'
MACADDR=02:00:00:23:65:1a
TYPE=Ethernet
....

Edit the new `ifcfg-0.0.0600` file as follows:

. Modify the `DEVICE` statement to reflect the contents of the `if_name` file from your `ccw` group.

. Modify the `IPADDR` statement to reflect the IP address of your new interface.

. Modify the `NETMASK` statement as needed.

. If the new interface is to be activated at boot time, then make sure `ONBOOT` is set to `yes`.

. Make sure the `SUBCHANNELS` statement matches the hardware addresses for your qeth device.

. Modify the `PORTNAME` statement or leave it out if it is not necessary in your environment.

. You can add any valid `sysfs` attribute and its value to the `OPTIONS` parameter. The {PRODUCT} installation program currently uses this to configure the layer mode (`layer2`) and the relative port number (`portno`) of `qeth` devices.
+
The `qeth` device driver default for OSA devices is now layer 2 mode. To continue using old `ifcfg` definitions that rely on the previous default of layer 3 mode, add `layer2=0` to the `OPTIONS` parameter.

`/etc/sysconfig/network-scripts/ifcfg-0.0.0600`

[literal,subs="+quotes,verbatim"]
....
# IBM QETH
DEVICE=enccw0.0.0600
BOOTPROTO=static
IPADDR=192.168.70.87
NETMASK=255.255.255.0
ONBOOT=yes
NETTYPE=qeth
SUBCHANNELS=0.0.0600,0.0.0601,0.0.0602
PORTNAME=OSAPORT
OPTIONS='layer2=1 portno=0'
MACADDR=02:00:00:b3:84:ef
TYPE=Ethernet
....

Changes to an `ifcfg` file only become effective after rebooting the system or after the dynamic addition of new network device channels by changing the system's I/O configuration (for example, attaching under z/VM). Alternatively, you can trigger the activation of a `ifcfg` file for network channels which were previously not active yet, by executing the following commands:

. Use the [command]`cio_ignore` utility to remove the network channels from the list of ignored devices and make them visible to Linux:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r read_device_bus_id,write_device_bus_id,data_device_bus_id
....
+
Replace _read_device_bus_id_,_write_device_bus_id_,_data_device_bus_id_ with the three device bus IDs representing a network device. For example, if the _read_device_bus_id_ is `0.0.0600`, the _write_device_bus_id_ is `0.0.0601`, and the _data_device_bus_id_ is `0.0.0602`:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`]  cio_ignore -r 0.0.0600,0.0.0601,0.0.0602
....

. To trigger the uevent that activates the change, issue:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo add > /sys/bus/ccw/devices/read-channel/uevent
....
+
For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo add > /sys/bus/ccw/devices/0.0.0600/uevent
....

. Check the status of the network device:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] lsqeth
....

. Now start the new interface:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ifup enccw0.0.0600
....

. Check the status of the interface:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ip addr show enccw0.0.0600
3: enccw0.0.0600:  <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
link/ether 3c:97:0e:51:38:17 brd ff:ff:ff:ff:ff:ff
inet 10.85.1.245/24 brd 10.34.3.255 scope global dynamic enccw0.0.0600
valid_lft 81487sec preferred_lft 81487sec
inet6 1574:12:5:1185:3e97:eff:fe51:3817/64 scope global noprefixroute dynamic
valid_lft 2591994sec preferred_lft 604794sec
inet6 fe45::a455:eff:d078:3847/64 scope link
valid_lft forever preferred_lft forever
....

. Check the routing for the new interface:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ip route
default via 10.85.1.245 dev enccw0.0.0600  proto static  metric 1024
12.34.4.95/24 dev enp0s25  proto kernel  scope link  src 12.34.4.201
12.38.4.128 via 12.38.19.254 dev enp0s25  proto dhcp  metric 1
192.168.122.0/24 dev virbr0  proto kernel  scope link  src 192.168.122.1
....

. Verify your changes by using the `ping` utility to ping the gateway or another host on the subnet of the new device:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ping -c 1 192.168.70.8
PING 192.168.70.8 (192.168.70.8) 56(84) bytes of data.
64 bytes from 192.168.70.8: icmp_seq=0 ttl=63 time=8.07 ms
....

. If the default route information has changed, you must also update `/etc/sysconfig/network` accordingly.

[[sect-post-installation-lcs-s390]]
==== Adding an LCS Device

The _LAN channel station_ (LCS) device driver supports 1000Base-T Ethernet on the OSA-Express2 and OSA-Express 3 features.

The `LCS` device driver assigns the following interface name for OSA-Express Fast Ethernet and Gigabit Ethernet devices: `enccw`pass:attributes[{blank}]pass:attributes[{blank}]_bus_ID_. The bus ID is composed of the channel subsystem ID, subchannel set ID, and device number, for example `enccw0.0.0a00`.

[[sect-post-installation-lcs-dynamic-s390]]
===== Dynamically Adding an LCS Device

. Load the device driver:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] modprobe lcs
....

. Use the [command]`cio_ignore` utility to remove the network channels from the list of ignored devices and make them visible to Linux:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r read_device_bus_id,write_device_bus_id
....
+
Replace _read_device_bus_id_ and _write_device_bus_id_ with the two device bus IDs representing a network device. For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r 0.0.09a0,0.0.09a1
....

. Create the group device:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo read_device_bus_id,write_device_bus_id > /sys/bus/ccwgroup/drivers/lcs/group
....

. Configure the device. OSA cards can provide up to 16 ports for a single CHPID. By default, the LCS group device uses port `0`. To use a different port, issue a command similar to the following:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo portno > /sys/bus/ccwgroup/drivers/lcs/device_bus_id/portno
....
+
Replace _portno_ with the port number you want to use.

. Set the device online:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo 1 > /sys/bus/ccwgroup/drivers/lcs/read_device_bus_id/online
....

. To find out what network device name has been assigned, enter the command:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ls -l /sys/bus/ccwgroup/drivers/lcs/read_device_bus_ID/net/
drwxr-xr-x 4 root root 0 2010-04-22 16:54 enccw0.0.0600
....

[[sect-post-installation-lcs-persistent-s390]]
===== Persistently Adding an LCS Device

The [command]`cio_ignore` commands are handled transparently for persistent device configurations and you do not need to free devices from the ignore list manually.

To add an LCS device persistently, follow these steps:

. Create a configuration script as file in `/etc/sysconfig/network-scripts/` with a name like `ifcfg-_device_pass:attributes[{blank}]`, where _device_ is the value found in the `if_name` file in the `qeth` group device that was created earlier, for example `enccw0.0.09a0`. The file should look similar to the following:
+
[literal,subs="+quotes,verbatim"]
....

# IBM LCS
DEVICE=enccw0.0.09a0
BOOTPROTO=static
IPADDR=10.12.20.136
NETMASK=255.255.255.0
ONBOOT=yes
NETTYPE=lcs
SUBCHANNELS=0.0.09a0,0.0.09a1
PORTNAME=0
OPTIONS=''
TYPE=Ethernet
....

. Modify the value of `PORTNAME` to reflect the LCS port number (`portno`) you would like to use. You can add any valid lcs sysfs attribute and its value to the optional `OPTIONS` parameter. See <<sect-post-installation-qeth-device-persistent-s390>> for the syntax.

. Set the `DEVICE` parameter as follows:
+
[literal,subs="+quotes,verbatim,macros"]
....
DEVICE=enccwpass:quotes[_bus_ID_]
....

. Issue an [command]`ifup` command to activate the device:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] ifup enccwbus_ID
....

Changes to an `ifcfg` file only become effective after rebooting the system. You can trigger the activation of a `ifcfg` file for network channels by executing the following commands:

. Use the [command]`cio_ignore` utility to remove the LCS device adapter from the list of ignored devices and make it visible to Linux:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r read_device_bus_id,write_device_bus_id
....
+
Replace _read_device_bus_id_ and _write_device_bus_id_ with the device bus IDs of the LCS device. For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] cio_ignore -r 0.0.09a0,0.0.09a1
....

. To trigger the uevent that activates the change, issue:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo add > /sys/bus/ccw/devices/read-channel/uevent
....
+
For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] echo add > /sys/bus/ccw/devices/0.0.09a0/uevent
....

[[sect-post-installation-configuring-network-root]]
==== Configuring a System{nbsp}z Network Device for Network Root File System

To add a network device that is required to access the root file system, you only have to change the boot options. The boot options can be in a parameter file (see <<chap-parameter-configuration-files-s390>>) or part of a `zipl.conf` on a DASD or FCP-attached SCSI LUN prepared with the [application]*zipl* boot loader. There is no need to recreate the initramfs.

[application]*Dracut*, the [application]*mkinitrd* successor that provides the functionality in the initramfs that in turn replaces [application]*initrd*, provides a boot parameter to activate network devices on System{nbsp}z early in the boot process: `rd.znet=`.

As input, this parameter takes a comma-separated list of the `NETTYPE` (qeth, lcs, ctc), two (lcs, ctc) or three (qeth) device bus IDs, and optional additional parameters consisting of key-value pairs corresponding to network device sysfs attributes. This parameter configures and activates the System{nbsp}z network hardware. The configuration of IP addresses and other network specifics works the same as for other platforms. See the [application]*dracut* documentation for more details.

The [application]*cio_ignore* commands for the network channels are handled transparently on boot.

Example boot options for a root file system accessed over the network through NFS:

[literal,subs="+quotes,verbatim"]
....
root=10.16.105.196:/nfs/nfs_root cio_ignore=all,!condev rd.znet=qeth,0.0.0a00,0.0.0a01,0.0.0a02,layer2=1,portno=0,portname=OSAPORT ip=10.16.105.197:10.16.105.196:10.16.111.254:255.255.248.0:nfs‑server.subdomain.domain:enccw0.0.09a0:none rd_NO_LUKS rd_NO_LVM rd_NO_MD rd_NO_DM LANG=en_US.UTF-8 SYSFONT=latarcyrheb-sun16 KEYTABLE=us
....