
:experimental:
include::entities.adoc[]

[[chap-installer-booting-ipl-s390]]
== Booting the Installation on IBM System{nbsp}z

The steps to perform the initial program boot (IPL) of the [application]*Anaconda* installation program depend on the environment (either z/VM or LPAR) in which {PRODUCT} will run.

[[sect-customizing-generic-prm-s390]]
=== Customizing boot parameters

Before you can begin the installation, you must configure some mandatory boot parameters. When installing through z/VM, these parameters must be configured before you boot in the `generic.prm` file. When installing on an LPAR, the [option]`rd.cmdline` parameter is set to `ask` by default, meaning that you will be given a prompt on which you can enter these boot parameters. In both cases, the required parameters are the same.

[NOTE]
====

Unlike Red{nbsp}Hat Enterprise Linux 6, which featured an interactive utility to assist network configuration, all network configuration must now be specified by the use of the following parameters, either by using a parameter file, or at the prompt.

====

Installation source::
+
An installation source must always be configured. Use the [option]`inst.repo=` option to specify the package source for the installation. See <<list-boot-options-sources>> for details and syntax.

Network devices::
+
Network configuration must be provided if network access will be required during the installation. If you plan to perform an unattended (Kickstart-based) installation using only local media such as a hard drive, network configuration can be omitted.
+
Use the [option]`ip=` option for basic network configuration, and other options listed in <<list-boot-options-network>> as required.
+
Also use the [option]`rd.znet=` kernel option, which takes a network protocol type, a comma delimited list of sub-channels, and, optionally, comma delimited `sysfs` parameter and value pairs. This parameter can be specified multiple times to activate multiple network devices.
+
For example:
+
[literal,subs="+quotes,verbatim"]
....

rd.znet=qeth,0.0.0600,0.0.0601,0.0.0602,layer2=1,portname=foo
rd.znet=ctc,0.0.0600,0.0.0601,protocol=bar

....

Storage devices::
+
At least one storage device must always be configured.
+
The [option]`rd.dasd=` option takes a Direct Access Storage Device (DASD) adapter device bus identifier and, optionally, comma separated `sysfs` parameter and value pairs, then activates the device. This parameter can be specified multiple times to activate multiple DASDs. Example:
+
[literal,subs="+quotes,verbatim"]
....

rd.dasd=0.0.0200,readonly=0
rd.dasd=0.0.0202,readonly=0

....
+
The [option]`rd.zfcp=` option takes a SCSI over FCP (zFCP) adapter device bus identifier, a world wide port name (WWPN), and a FCP LUN, then activates the device. This parameter can be specified multiple times to activate multiple zFCP devices. Example:
+
[literal,subs="+quotes,verbatim"]
....
rd.zfcp=0.0.4000,0x5005076300C213e9,0x5022000000000000
....

Kickstart options::
+
If you are using a Kickstart file to perform an automatic installation, you must always specify the location of the Kickstart file using the [option]`inst.ks=` option. For an unattended, fully automatic Kickstart installation, the [option]`inst.cmdline` option is also useful. See <<sect-parameter-configuration-files-kickstart-s390>> for additional information.

An example customized `generic.prm` file containing all mandatory parameters look similar to the following example:

[[exam-modified-generic-prm]]
.Customized generic.prm file
====

[literal,subs="+quotes,verbatim"]
....
ro ramdisk_size=40000 cio_ignore=all,!condev
inst.repo=http://example.com/path/to/repository
rd.znet=qeth,0.0.0600,0.0.0601,0.0.0602,layer2=1,portno=0,portname=foo
ip=192.168.17.115::192.168.17.254:24:foobar.systemz.example.com:enccw0.0.0600:none
nameserver=192.168.17.1
rd.dasd=0.0.0200 rd.dasd=0.0.0202
rd.zfcp=0.0.4000,0x5005076300C213e9,0x5022000000000000
inst.ks=http://example.com/path/to/kickstart
....

====

Some installation methods also require a file with a mapping of the location of installation data in the file system of the DVD or FTP server and the memory locations where the data is to be copied. The file is typically named `generic.ins`, and contains file names for the initial RAM disk, kernel image, and parameter file (`generic.prm`) and a memory location for each file. An example `generic.ins` will look similar to the following example:

[[exam-generic-ins]]
.Sample generic.ins file
====

[literal,subs="+quotes,verbatim"]
....
images/kernel.img 0x00000000
images/initrd.img 0x02000000
images/genericdvd.prm 0x00010480
images/initrd.addrsize 0x00010408
....

====

A valid `generic.ins` file is provided by Red{nbsp}Hat along with all other files required to boot the installer. Modify this file only if you want to, for example, load a different kernel version than default.

[[sect-installation-source-hdd-s390x]]
=== Considerations for Hard Drive Installation on IBM System{nbsp}z

If you want to boot the installation program from a hard drive, you can optionally install the [application]*zipl* boot loader on the same (or a different) disk. Be aware that [application]*zipl* only supports one boot record per disk. If you have multiple partitions on a disk, they all "share" the disk's single boot record.

To prepare a hard drive to boot the installation program, install the [application]*zipl* boot loader on the hard drive by entering the following command:

[literal,subs="+quotes,verbatim,macros"]
....

pass:quotes[`#`] zipl -V -t /mnt/ -i /mnt/images/kernel.img -r /mnt/images/initrd.img -p /mnt/images/generic.prm

....

See <<sect-customizing-generic-prm-s390>> for details on customizing boot parameters in the `generic.prm` configuration file.

[[sect-installing-zvm-s390]]
=== Installing under z/VM

When installing under z/VM, you can boot from:

* the z/VM virtual reader

* a DASD or an FCP-attached SCSI device prepared with the [application]*zipl* boot loader

* an FCP-attached SCSI DVD drive

Log on to the z/VM guest virtual machine chosen for the Linux installation. You can use the [application]*x3270* or [application]*c3270* terminal emulator, available in the [package]*x3270-text* package in {PRODUCT}, to log in to z/VM from other Linux systems. Alternatively, use the IBM 3270 terminal emulator on the IBM System{nbsp}z Hardware Management Console (HMC). If you are working from a machine with a Microsoft Windows operating system, Jolly Giant (link:++http://www.jollygiant.com/++[]) offers an SSL-enabled 3270 emulator. A free native Windows port of [application]*c3270* called [application]*wc3270* also exists.

[NOTE]
====

If your 3270 connection is interrupted and you cannot log in again because the previous session is still active, you can replace the old session with a new one by entering the following command on the z/VM logon screen:

[literal,subs="+quotes,verbatim,macros"]
....
[command]`logon _user_ here`
....

Replace _user_ with the name of the z/VM guest virtual machine. Depending on whether an external security manager, for example RACF, is used, the logon command might vary.

====

If you are not already running [application]*CMS* (single-user operating system shipped with z/VM) in your guest, boot it now by entering the command:

[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp ipl cms`
....

Be sure not to use CMS disks such as your A disk (often device number 0191) as installation targets. To find out which disks are in use by CMS, use the following query:

[literal,subs="+quotes,verbatim,macros"]
....
[command]`query disk`
....

You can use the following CP (z/VM Control Program, which is the z/VM hypervisor) query commands to find out about the device configuration of your z/VM guest virtual machine:

* Query the available main memory, which is called _storage_ in System{nbsp}z terminology. Your guest should have at least 1 GB of main memory.
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp query virtual storage`
....

* Query available network devices by type:
+
[command]`osa`::
+
OSA - CHPID type OSD, real or virtual (VSWITCH or GuestLAN), both in QDIO mode
+
[command]`hsi`::
+
HiperSockets - CHPID type IQD, real or virtual (GuestLAN type Hipers)
+
[command]`lcs`::
+
LCS - CHPID type OSE
+
For example, to query all of the network device types mentioned above, run:
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp query virtual osa`
....

* Query available DASDs. Only those that are flagged `RW` for read-write mode can be used as installation targets:
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp query virtual dasd`
....

* Query available FCP channels:
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp query virtual fcp`
....

[[sect-installing-zvm-reader-s390]]
==== Using the z/VM Reader

Perform the following steps to boot from the z/VM reader:

. If necessary, add the device containing the z/VM TCP/IP tools to your CMS disk list. For example:
+
[literal,subs="+quotes,verbatim,macros"]
....

cp link tcpmaint 592 592
acc 592 _fm_

....
+
Replace _fm_ with any `FILEMODE` letter.

. Execute the command:
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`ftp _host_pass:attributes[{blank}]`
....
+
Where _host_ is the host name or IP address of the FTP server that hosts the boot images (`kernel.img` and `initrd.img`).

. Log in and execute the following commands. Use the [option]`(repl` option if you are overwriting existing `kernel.img`, `initrd.img`, `generic.prm`, or `redhat.exec` files:
+
[literal,subs="+quotes,verbatim,macros"]
....

[command]`cd _/location/of/install-tree_pass:attributes[{blank}]/images/`
[command]`ascii` 
[command]`get generic.prm (repl` 
[command]`get redhat.exec (repl` 
[command]`locsite fix 80` 
[command]`binary` 
[command]`get kernel.img (repl` 
[command]`get initrd.img (repl` 
[command]`quit`

....

. Optionally, check whether the files were transferred correctly by using the CMS command [command]`filelist` to show the received files and their format. It is important that `kernel.img` and `initrd.img` have a fixed record length format denoted by `F` in the Format column and a record length of 80 in the `Lrecl` column. For example:
+
[literal,subs="+quotes,verbatim"]
....

VMUSER FILELIST A0 V 169 Trunc=169 Size=6 Line=1 Col=1 Alt=0
Cmd Filename	Filetype	Fm	Format	Lrecl	Records	Blocks	Date	Time
REDHAT	EXEC		B1	V	22	1 	1	4/15/10	9:30:40
GENERIC	PRM		B1	V	44	1	1	4/15/10	9:30:32
INITRD	IMG		B1	F	80	118545	2316	4/15/10	9:30:25
KERNEL	IMG		B1	F	80	74541	912	4/15/10	9:30:17

....
+
Press kbd:[PF3] to quit [command]`filelist` and return to the CMS prompt.

. Customize boot parameters in `generic.prm` as necessary. See <<sect-customizing-generic-prm-s390>> for details.
+
Another way to configure storage and network devices is by using a CMS configuration file. In such a case, add the `CMSDASD=` and `CMSCONFFILE=` parameters to `generic.prm`. See <<sect-parameter-configuration-files-zvm-s390>> for more details.

. Finally, execute the REXX script `redhat.exec` to boot the installation program:
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`redhat`
....

[[sect-installing-zvm-prepared-dasd-s390]]
==== Using a Prepared DASD

Boot from the prepared DASD and select the [application]*zipl* boot menu entry referring to the {PRODUCT} installation program. Use a command of the following form:

[literal,subs="+quotes,verbatim"]
....
cp ipl DASD_device_number loadparm boot_entry_number
....

Replace _DASD_device_number_ with the device number of the boot device, and _boot_entry_number_ with the [application]*zipl* configuration menu for this device. For example:

[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp ipl eb1c loadparm 0`
....

[[sect-installing-zvm-prepared-fcp-scsi-s390]]
==== Using a Prepared FCP-attached SCSI Disk

Perform the following steps to boot from a prepared FCP-attached SCSI disk:

. Configure the SCSI boot loader of z/VM to access the prepared SCSI disk in the FCP Storage Area Network. Select the prepared [application]*zipl* boot menu entry referring to the {PRODUCT} installation program. Use a command of the following form:
+
[literal,subs="+quotes,verbatim"]
....
cp set loaddev portname WWPN lun LUN bootprog boot_entry_number
....
+
Replace _WWPN_ with the World Wide Port Name of the storage system and _LUN_ with the Logical Unit Number of the disk. The 16-digit hexadecimal numbers must be split into two pairs of eight digits each. For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp set loaddev portname 50050763 050b073d lun 40204011 00000000 bootprog 0`
....

. Optionally, confirm your settings with the command:
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`query loaddev`
....

. Boot the FCP device connected with the storage system containing the disk with the following command:
+
[literal,subs="+quotes,verbatim"]
....
cp ipl FCP_device 
....
+
For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp ipl fc00`
....

[[sect-installing-zvm-prepared-fcp-dvd-s390]]
==== Using an FCP-attached SCSI DVD Drive

This requires a SCSI DVD drive attached to an FCP-to-SCSI bridge which is in turn connected to an FCP adapter in your System{nbsp}z. The FCP adapter must be configured and available under z/VM.

. Insert your {PRODUCT} for System{nbsp}z DVD into the DVD drive.

. Configure the SCSI boot loader of z/VM to access the DVD drive in the FCP Storage Area Network and specify `1` for the boot entry on the {PRODUCT} for System{nbsp}z DVD. Use a command of the following form:
+
[literal,subs="+quotes,verbatim"]
....
cp set loaddev portname WWPN lun FCP_LUN bootprog 1
....
+
Replace _WWPN_ with the WWPN of the FCP-to-SCSI bridge and _FCP_LUN_ with the LUN of the DVD drive. The 16-digit hexadecimal numbers must be split into two pairs of eight characters each. For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp set loaddev portname 20010060 eb1c0103 lun 00010000 00000000 bootprog 1`
....

. Optionally, confirm your settings with the command:
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp query loaddev`
....

. IPL on the FCP device connected with the FCP-to-SCSI bridge.
+
[literal,subs="+quotes,verbatim"]
....
cp ipl FCP_device
....
+
For example:
+
[literal,subs="+quotes,verbatim,macros"]
....
[command]`cp ipl fc00`
....

[[sect-installing-lpar-s390]]
=== Installing in an LPAR

When installing in a _logical partition_ (LPAR), you can boot from:

* an FTP server

* a DASD or an FCP-attached SCSI drive prepared with the [application]*zipl* boot loader

* an FCP-attached SCSI DVD drive

Perform these common steps first:

. Log in on the IBM System{nbsp}z _Hardware Management Console_ (HMC) or the _Support Element_ (SE) as a user with sufficient privileges to install a new operating system to an LPAR. The `SYSPROG` user is recommended.

. Select `Images`, then select the LPAR to which you want to install. Use the arrows in the frame on the right side to navigate to the CPC Recovery menu.

. Double-click `Operating System Messages` to show the text console on which Linux boot messages will appear.

Continue with the procedure for your installation source.

[NOTE]
====

Once you finish this procedure and one of the following ones depending on your installation source, the installation will begin. The installer will then prompt you to provide additional boot parameters. Required parameters are described in <<sect-customizing-generic-prm-s390>>.

====

[[sect-installing-lpar-ftp-s390]]
==== Using an FTP Server

. Double-click `Load from CD-ROM, DVD, or Server`.

. In the dialog box that follows, select `FTP Source`, and enter the following information:
+
** `Host Computer` - Host name or IP address of the FTP server you want to install from, for example `ftp.redhat.com`
+
** `User ID` - Your user name on the FTP server. Or, specify `anonymous`.
+
** `Password` - Your password. Use your email address if you are logging in as `anonymous`.
+
** `Account (optional)` - Leave this field empty.
+
** `File location (optional)` - Directory on the FTP server holding the {PRODUCT} for System{nbsp}z, for example `/rhel/s390x/`.

. Click `Continue`.

. In the dialog that follows, keep the default selection of `generic.ins` and click `Continue`.

[[sect-installing-lpar-dasd-s390]]
==== Using a Prepared DASD

. Double-click `Load`.

. In the dialog box that follows, select `Normal` as the `Load type`.

. As `Load address`, fill in the device number of the DASD.

. As `Load parameter`, fill in the number corresponding the [application]*zipl* boot menu entry that you prepared for booting the {PRODUCT} installation program.

. Click the btn:[OK] button.

[[sect-installing-lpar-fcp-scsi-s390]]
==== Using a Prepared FCP-attached SCSI Disk

. Double-click `Load`.

. In the dialog box that follows, select `SCSI` as the `Load type`.

. As `Load address`, fill in the device number of the FCP channel connected with the SCSI disk.

. As `World wide port name`, fill in the WWPN of the storage system containing the disk as a 16-digit hexadecimal number.

. As `Logical unit number`, fill in the LUN of the disk as a 16-digit hexadecimal number.

. As `Boot program selector`, fill in the number corresponding the [application]*zipl* boot menu entry that you prepared for booting the {PRODUCT} installation program.

. Leave the `Boot record logical block address` as `0` and the `Operating system specific load parameters` empty.

. Click the btn:[OK] button.

[[sect-installing-lpar-fcp-dvd-s390]]
==== Using an FCP-attached SCSI DVD Drive

This requires a SCSI DVD drive attached to an FCP-to-SCSI bridge which is in turn connected to an FCP adapter in your System{nbsp}z machine. The FCP adapter must be configured and available in your LPAR.

. Insert your {PRODUCT} for System{nbsp}z DVD into the DVD drive.

. Double-click `Load`.

. In the dialog box that follows, select `SCSI` as the `Load type`.

. As `Load address`, fill in the device number of the FCP channel connected with the FCP-to-SCSI bridge.

. As `World wide port name`, fill in the WWPN of the FCP-to-SCSI bridge as a 16-digit hexadecimal number.

. As `Logical unit number`, fill in the LUN of the DVD drive as a 16-digit hexadecimal number.

. As `Boot program selector`, fill in the number `1` to select the boot entry on the {PRODUCT} for System{nbsp}z DVD.

. Leave the `Boot record logical block address` as `0` and the `Operating system specific load parameters` empty.

. Click the btn:[OK] button.