
:experimental:
include::entities.adoc[]

[[chap-installation-planning-x86]]
== Planning for Installation on 64-bit AMD, Intel, and ARM Systems

This chapter outlines the decisions and preparations you will need to make when deciding how to proceed with the installation.

[[sect-installation-planning-upgrade-or-install-x86]]
=== Upgrade or Install?

There are two procedures available for upgrading your current system to the next major version of {PRODUCT}. To decide which procedure is the right one for your system, read the following descriptions:

Clean Install::
+
A clean install is performed by backing up all data from the system, formatting disk partitions, performing an installation of {PRODUCT} from installation media, and then restoring any user data.
+
[NOTE]
====

This is the recommended method for upgrading between major versions of {PRODUCT}.

====

In-Place Upgrade::
+
An in-place upgrade is a way of upgrading your system without removing the older version first. The procedure requires installing the migration utilities available for your system and running them as any other software. In {PRODUCT}, the [application]*Preupgrade Assistant* assesses your current system and identifies potential problems you might encounter during or after the upgrade. It also performs minor fixes and modifications to the system. The [application]*Red{nbsp}Hat Upgrade Tool* utility downloads the packages and performs the actual upgrade. An in-place upgrade requires a lot of troubleshooting and planning and should only be done if there is no other choice. For more information on the [application]*Preupgrade Assistant*, see <<chap-upgrading-your-current-system>>.
+
[WARNING]
====

Never perform an in-place upgrade on a production system without first testing it on a cloned backup copy of the system.

====

[[sect-installation-planning-hardware-compatibility-x86]]
=== Is Your Hardware Compatible?

{PRODUCT}{nbsp}7 should be compatible with most hardware in systems that were factory built within the last two years. Hardware compatibility is a particularly important concern if you have an older or custom-built system. Because hardware specifications change almost daily, it is recommended that all systems be checked for compatibility.

The most recent list of supported hardware can be found in the [citetitle]_Red{nbsp}Hat Hardware Compatibility List_, available online at link:++https://access.redhat.com/ecosystem/search/#/category/Server++[]. Also see link:++https://access.redhat.com/site/articles/rhel-limits++[{PRODUCT} technology capabilities and limits] for general information about system requirements.

[[sect-installation-planning-supported-hardware-x86]]
=== Supported Installation Targets

An installation target is a storage device that will store {PRODUCT} and boot the system. {PRODUCT} supports the following installation targets for AMD, Intel, and ARM systems:

* Storage connected by a standard internal interface, such as SCSI, SATA, or SAS

* BIOS/firmware RAID devices

* Fibre Channel Host Bus Adapters and multipath devices. Some can require vendor-provided drivers.

* Xen block devices on Intel processors in Xen virtual machines.

* VirtIO block devices on Intel processors in KVM virtual machines.

Red{nbsp}Hat does not support installation to USB drives or SD memory cards. For information about the support for third-party virtualization technologies, see the [citetitle]_Red{nbsp}Hat Hardware Compatibility List_, available online at link:++https://hardware.redhat.com++[].

[[sect-installation-planning-system-specifications-x86]]
=== System Specifications List

The installation program automatically detects and installs your computer's hardware and you do not usually need to supply the installation program with any specific details about your system. However, when performing certain types of installation, it is important to know specific details about your hardware. For this reason, it is recommended that you record the following system specifications for reference during the installation, depending on your installation type.

* If you plan to use a customized partition layout, record:
+
** The model numbers, sizes, types, and interfaces of the hard drives attached to the system. For example, Seagate ST3320613AS 320 GB on SATA0, Western Digital WD7500AAKS 750 GB on SATA1. This will allow you to identify specific hard drives during the partitioning process.

* If you are installing {PRODUCT} as an additional operating system on an existing system, record:
+
** Information about the partitions used on the system. This information can include file system types, device node names, file system labels, and sizes. This will allow you to identify specific partitions during the partitioning process. Remember that different operating systems identify partitions and drives differently, therefore even if the other operating system is a Unix operating system, the device names can be reported by {PRODUCT} differently. This information can usually be found by executing the equivalent of the [command]`mount` command and [command]`blkid` command and in the `/etc/fstab` file.
+
If you have other operating systems already installed, the {PRODUCT}{nbsp}7 installation program attempts to automatically detect and configure to boot them. You can manually configure any additional operating systems if they are not detected properly. For more information, see <<sect-bootloader-x86>>.

* If you plan to install from an image on a local hard drive:
+
** The hard drive and directory that holds the image.

* If you plan to install from a network location:
+
** The make and model numbers of the network adapters on your system. For example, Netgear GA311. This will allow you to identify adapters when manually configuring the network.
+
** IP, DHCP, and BOOTP addresses
+
** Netmask
+
** Gateway IP address
+
** One or more name server IP addresses (DNS)
+
** The location of the installation source on an FTP server, HTTP (web) server, HTTPS (web) server, or NFS server.
+
If any of these networking requirements or terms are unfamiliar to you, contact your network administrator for assistance.

* If you plan to install on an iSCSI target:
+
** The location of the iSCSI target. Depending on your network, you might also need a CHAP user name and password, and perhaps a reverse CHAP user name and password.

* If your computer is part of a domain:
+
** You should verify that the domain name will be supplied by the DHCP server. If not, you will need to input the domain name manually during installation.

[[sect-installation-planning-disk-space-memory-x86]]
=== Disk Space and Memory Requirements

{PRODUCT}, like most modern operating systems, uses _disk partitions_. When you install {PRODUCT}, you might have to work with disk partitions. For more information, see <<appe-disk-partitions-overview>>.

If you have other operating systems installed on your system, the disk space they use must be separate from the disk space used by {PRODUCT}.

[NOTE]
====

For AMD64/Intel{nbsp}64 and ARM systems, at least two partitions (`/` and `swap`) must be dedicated to {PRODUCT}.

====

To install {PRODUCT}, you must have a minimum of 10 GiB of space in either unpartitioned disk space or in partitions which can be deleted. For more information on partition and disk space recommendations, see the recommended partitioning sizes discussed in <<sect-recommended-partitioning-scheme-x86>>.

{PRODUCT} requires minimum the following amount of RAM:

[options="header"]
|===
|Installation type|Minimum required RAM
|Local media installation (USB, DVD)|768 MiB
|NFS network installation|768 MiB
|HTTP, HTTPS, or FTP network installation|1.5 GiB
|===

[NOTE]
====

It may be possible to perform the installation with less memory than listed in this section. However, the exact requirements depend heavily on your environment and exact installation path, and they also change with each new release. Determining the absolute minimum required RAM for your specific use case therefore requires you to test various configurations, and periodically re-test with each new release.

====

Installing {PRODUCT} using a Kickstart file has the same minimum RAM requirements as a manual installation. However, if you use a Kickstart file that runs commands which require additional memory or write data to the RAM disk, additional RAM might be necessary.

For more information about the minimum requirements and technology limits of Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7, see the [citetitle]_link:++https://access.redhat.com/articles/rhel-limits++[Red{nbsp}Hat Enterprise{nbsp}Linux technology capabilities and limits]_ article on the Red{nbsp}Hat Customer Portal.

[[sect-installation-planning-partitioning-raid-x86]]
=== RAID and Other Disk Devices

Some storage technology requires special consideration when using {PRODUCT}. Generally, it is important to understand how these technologies are configured, visible to {PRODUCT}, and how support for them might have changed between major versions.

[[sect-installation-planning-hardware-raid-x86]]
==== Hardware RAID

RAID (Redundant Array of Independent Disks) allows a group, or array, of drives to act as a single device. Configure any RAID functions provided by the mainboard of your computer, or attached controller cards, before you begin the installation process. Each active RAID array appears as one drive within {PRODUCT}.

[[sect-installation-planning-software-raid-x86]]
==== Software RAID

On systems with more than one hard drive, you can use the {PRODUCT} installation program to operate several of the drives as a Linux software RAID array. With a software RAID array, RAID functions are controlled by the operating system rather than dedicated hardware. These functions are explained in detail in <<sect-custom-partitioning-x86>>.

[NOTE]
====

When a pre-existing RAID array's member devices are all unpartitioned disks/drives, the installer will treat the array itself as a disk and will not provide a way to remove the array.

====

[[sect-installation-planning-usb-disks-x86]]
==== USB Disks

You can connect and configure external USB storage after installation. Most such devices are recognized by the kernel and available for use at that time.

Some USB drives might not be recognized by the installation program. If configuration of these disks at installation time is not vital, disconnect them to avoid potential problems.

[[sect-installation-planning-intel-bios-raid-sets-x86]]
==== Considerations for Intel BIOS RAID Sets

{PRODUCT}{nbsp}7 uses [application]*mdraid* for installation onto Intel BIOS RAID sets. These sets are detected automatically during the boot process and their device node paths can change from boot to boot. For this reason, local modifications to `/etc/fstab`, `/etc/crypttab` or other configuration files which refer to devices by their device node paths might not work in {PRODUCT}{nbsp}7. Therefore, you should replace device node paths (such as `/dev/sda`) with file system labels or device UUIDs instead. You can find the file system labels and device UUIDs using the [command]`blkid` command.

[[sect-installation-planning-iscsi-remote-boot-x86]]
==== Considerations for Intel BIOS iSCSI Remote Boot

If you are installing using Intel iSCSI Remote Boot, all attached iSCSI storage devices must be disabled, otherwise the installation will succeed but the installed system will not boot.

[[sect-installation-planning-boot-method-x86]]
=== Choose an Installation Boot Method

You can use several methods to boot the {PRODUCT}{nbsp}7 installation program. The method you choose depends upon your installation media.

Your system's firmware (BIOS of UEFI) settings might need to be changed to allow booting from removable media such as a DVD or a USB flash drive. See <<sect-installation-booting-x86>> for information.

[NOTE]
====

Installation media must remain mounted throughout installation, including during execution of the [command]`%post` section of a kickstart file.

====

Full installation DVD or USB drive::
+
You can create bootable media from the full installation DVD ISO image. In this case, a single DVD or USB drive can be used to complete the entire installation - it will serve both as a boot device and as an installation source for installing software packages. See <<chap-making-media>> for instructions on how to make a full installation DVD or USB drive.

Minimal boot CD, DVD or USB Flash Drive::
+
A minimal boot CD, DVD or USB flash drive is created using a small ISO image, which only contains data necessary to boot the system and start the installation. If you use this boot media, you will need an additional installation source from which packages will be installed. See <<sect-making-usb-media>> for instructions on making boot CDs, DVDs and USB flash drives.

PXE Server::
+
A _preboot execution environment_ (PXE) server allows the installation program to boot over the network. After you boot the system, you complete the installation from a different installation source, such as a local hard drive or a location on a network. For more information on PXE servers, see <<chap-installation-server-setup>>.

[[sect-installation-planning-kickstart-x86]]
=== Automating the Installation with Kickstart

{PRODUCT}{nbsp}7 offers a way to partially or fully automate the installation process using a _Kickstart file_. Kickstart files contain answers to all questions normally asked by the installation program, such as what time zone do you want the system to use, how should the drives be partitioned or which packages should be installed. Providing a prepared Kickstart file at the beginning of the installation therefore allows you to perform the entire installation (or parts of it) automatically, without need for any intervention from the user. This is especially useful when deploying {PRODUCT} on a large number of systems at once.

In addition to allowing you to automate the installation, Kickstart files also provide more options regarding software selection. When installing {PRODUCT} manually using the graphical installation interface, your software selection is limited to pre-defined environments and add-ons. A Kickstart file allows you to install or remove individual packages as well.

For instructions about creating a Kickstart file and using it to automate the installation, see <<chap-kickstart-installations>>.

[[sect-installation-planning-beta-secure-boot]]
=== Using a Beta Release with UEFI Secure Boot

[NOTE]
====

This section _only_ concerns Beta releases of {PRODUCT}{nbsp}7.

====

The UEFI Secure Boot technology requires that the operating system kernel must be signed with a recognized private key in order to be able to boot. In every beta release of {PRODUCT}{nbsp}7, the kernel is signed with a Red{nbsp}Hat Beta-specific private key, which is different from the more common Red{nbsp}Hat key used to sign kernels in a General Availability (non-Beta) releases.

The Beta private key will likely not be recognized by your hardware, which means that any Beta release of {PRODUCT} 7 will not be able to boot. In order to use a Beta release with UEFI Secure Boot enabled, you need to add the Red{nbsp}Hat Beta public key to your system using the _Machine Owner Key_ (MOK) facility.

The procedure to add the Red{nbsp}Hat Beta key to your system is below.

[[proc-add-uefi-secure-boot-key]]
.Adding a Custom Private Key for UEFI Secure Boot
. First, disable UEFI Secure Boot on the system, and install {PRODUCT}{nbsp}7 normally.

. After the installation finishes, the system will reboot. Secure Boot should still be disabled at this point. Reboot the system, log in and, if applicable, go through the Initial Setup screens as described in <<chap-initial-setup>>.

. After finishing the first boot and going through Initial Setup, install the [package]*kernel-doc* package if not installed already:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] yum install kernel-doc
....
+
This package provides a certificate file which contains the Red Hat CA public Beta key, located in `/usr/share/doc/kernel-keys/pass:attributes[{blank}]_kernel-version_pass:attributes[{blank}]/kernel-signing-ca.cer`, where _kernel-version_ is the kernel version string without the platform architecture suffix - for example, `3.10.0-686.el7`.

. Execute the following commands to enroll the public key into the system Machine Owner Key (MOK) list:
+
[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] kr=$(uname -r)
pass:quotes[`#`] mokutil --import /usr/share/doc/kernel-keys/${kr%.$(uname -p)}/kernel-signing-ca.cer

....
+
Enter a password of your choosing when prompted.
+
[NOTE]
====

Make sure to remember the password. It is required to finish this procedure as well as to remove the imported key when it is no longer needed.

====

. Reboot the system again. During startup you will be prompted to confirm that you want to complete the pending key enrollment request. Select yes, and provide the password which you set earlier using the [command]`mokutil` command in the previous step. The system will reboot again after you do so, and the key will be imported into the system firmware. You can turn on Secure Boot on this or any subsequent reboot.

[WARNING]
====

Remove the imported Beta public key when you no longer need it.

If you install a final (General Availability) release of {PRODUCT}{nbsp}7, or when you install a different operating system, you should remove the imported key. If you have _only_ imported this public key, you can use the following command to reset the MOK:

[literal,subs="+quotes,verbatim,macros"]
....
pass:quotes[`#`] mokutil --reset
....

After the next reboot, the firmware will prompt you for a confirmation and the password you created when importing the key. The key will be removed from the MOK after providing the correct password, and the system will revert to its original state.

====