
:experimental:
include::entities.adoc[]

[[chap-installation-planning-s390]]
== Planning for Installation on IBM System{nbsp}z

[[sect-pre-installation-s390]]
=== Pre-installation

{PRODUCT}{nbsp}7 runs on zEnterprise{nbsp}196 or later IBM mainframe systems.

The installation process assumes that you are familiar with the IBM System{nbsp}z and can set up _logical partitions_ (LPARs) and z/VM guest virtual machines. For additional information on System{nbsp}z, see link:++http://www.ibm.com/systems/z++[].

For installation of {PRODUCT} on System{nbsp}z, Red{nbsp}Hat supports DASD (Direct Access Storage Device) and FCP (Fiber Channel Protocol) storage devices.

Before you install {PRODUCT}, you must decide on the following:

* Decide whether you want to run the operating system on an LPAR or as a z/VM guest operating system.

* Decide if you need swap space and if so, how much. Although it is possible (and recommended) to assign enough memory to a z/VM guest virtual machine and let z/VM do the necessary swapping, there are cases where the amount of required RAM is hard to predict. Such instances should be examined on a case-by-case basis. See <<sect-recommended-partitioning-scheme-s390>>.

* Decide on a network configuration. {PRODUCT}{nbsp}7 for IBM System{nbsp}z supports the following network devices:
+
** Real and virtual _Open Systems Adapter_ (OSA)
+
** Real and virtual HiperSockets
+
** _LAN channel station_ (LCS) for real OSA

You require the following hardware:

* Disk space. Calculate how much disk space you need and allocate sufficient disk space on DASDsfootnote:[pass:attributes[{blank}]_Direct Access Storage Devices_ (DASDs) are hard disks that allow a maximum of three partitions per device. For example, `dasda` can have partitions `dasda1`, `dasda2`, and `dasda3`.] or SCSIfootnote:[Using the SCSI-over-Fibre Channel device driver (the `zfcp` device driver) and a switch, SCSI LUNs can be presented to Linux on System{nbsp}z as if they were locally attached SCSI drives.] disks. You require at least 10{nbsp}GB for a server installation, and 20{nbsp}GB if you want to install all packages. You also require disk space for any application data. After the installation, you can add or delete more DASD or SCSI disk partitions.
+
The disk space used by the newly installed {PRODUCT} system (the Linux instance) must be separate from the disk space used by other operating systems you have installed on your system.
+
For more information about disks and partition configuration, see <<sect-recommended-partitioning-scheme-s390>>.

* RAM. Acquire 1{nbsp}GB (recommended) for the Linux instance. With some tuning, an instance might run with as little as 512{nbsp}MB RAM.

[NOTE]
====

When initializing swap space on an FBA (_Fixed Block Architecture_) DASD using the [application]*SWAPGEN* utility, the [option]`FBAPART` option must be used.

====

[[sect-installation-overview-s390]]
=== Overview of the System{nbsp}z Installation Procedure

You can install {PRODUCT} on System{nbsp}z interactively or in unattended mode. Installation on System{nbsp}z differs from installation on other architectures in that it is typically performed over a network and not from a local media. The installation consists of two phases:

. Booting the Installation
Connect with the mainframe, then perform an _initial program load_ (IPL), or boot, from the medium containing the installation program. See <<chap-installer-booting-ipl-s390>> for details.

. Anaconda
Use the [application]*Anaconda* installation program to configure network, specify language support, installation source, software packages to be installed, and to perform the rest of the installation. See <<chap-installing-using-anaconda-s390>> for more information.

[[sect-installation-overview-booting-s390]]
==== Booting the Installation

After establishing a connection with the mainframe, you need to perform an initial program load (IPL), or boot, from the medium containing the installation program. This document describes the most common methods of installing {PRODUCT} on System{nbsp}z. In general, you can use any method to boot the Linux installation system, which consists of a kernel (`kernel.img`) and initial RAM disk (`initrd.img`) with at least the parameters in the `generic.prm` file. Additionally, a `generic.ins` file is loaded which determines file names and memory addresses for the initrd, kernel and generic.prm.

The Linux installation system is also called the _installation program_ in this book.

The control point from where you can start the IPL process depends on the environment where your Linux is to run. If your Linux is to run as a z/VM guest operating system, the control point is the _control program_ (CP) of the hosting z/VM. If your Linux is to run in LPAR mode, the control point is the mainframe's _Support Element_ (SE) or an attached IBM System{nbsp}z _Hardware Management Console_ (HMC).

You can use the following boot media only if Linux is to run as a guest operating system under z/VM:

* z/VM reader - see <<sect-installing-zvm-reader-s390>> for details.

You can use the following boot media only if Linux is to run in LPAR mode:

* SE or HMC through a remote FTP server - see <<sect-installing-lpar-ftp-s390>> for details.

* SE or HMC DVD - see <<sect-installing-lpar-fcp-dvd-s390>> for details.

You can use the following boot media for both z/VM and LPAR:

* DASD - see <<sect-installing-zvm-prepared-dasd-s390>> for z/VM or <<sect-installing-lpar-dasd-s390>> for LPAR.

* SCSI device that is attached through an FCP channel - see <<sect-installing-zvm-prepared-fcp-scsi-s390>> for z/VM or <<sect-installing-lpar-fcp-scsi-s390>> for LPAR.

* FCP-attached SCSI DVD - see <<sect-installing-zvm-prepared-fcp-dvd-s390>> for z/VM or <<sect-installing-lpar-fcp-dvd-s390>> for LPAR

If you use DASD and FCP-attached SCSI devices (except SCSI DVDs) as boot media, you must have a configured `zipl` boot loader.

[[sect-installation-overview-anaconda-s390]]
==== Installation using Anaconda

In the second installation phase, you will use the [application]*Anaconda* installation program in graphical, text-based, or command-line mode:

Graphical Mode::
+
Graphical installation is done through a VNC client. You can use your mouse and keyboard to navigate through the screens, click buttons, and type into text fields. For more information on performing a graphical installation using VNC, see <<chap-vnc-installations>>.

Text-based Mode::
+
This interface does not offer all interface elements of the GUI and does not support all settings. Use this for interactive installations if you cannot use a VNC client. For more information about text-based installations, see <<sect-installation-text-mode-s390>>.

Command-line Mode::
+
This is intended for automated and non-interactive installations on System{nbsp}z. Note that if the installation program encounters an invalid or missing kickstart command, the system will reboot. For more information about automated installation, see <<chap-kickstart-installations>>.

In {PRODUCT}{nbsp}7 the text-based installation has been reduced to minimize user interaction. Features like installation on FCP-attached SCSI devices, customizing partition layout, or package add-on selection are only available with the graphical user interface installation. Use the graphical installation whenever possible. See <<chap-installing-using-anaconda-s390>> for more details.