
:experimental:
include::entities.adoc[]

[[appe-technical-references]]
== Other Technical Documentation

Both [application]*Anaconda* and {PRODUCT} systems use a common set of software components. For detailed information on key technologies, see the web sites listed below.

Boot Loader::
+
{PRODUCT} uses the [command]`GRUB2` boot loader. See the corresponding chapter in the [citetitle]_link:++https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/ch-Working_with_the_GRUB_2_Boot_Loader.html++[RRed{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 System Administrator's Guide]_.

Storage Management::
+
Logical Volume Management (LVM) provides administrators with a range of facilities to manage storage. By default, the {PRODUCT} installation process formats drives as LVM volumes. For further details about LVM, see the [citetitle]_link:++https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Logical_Volume_Manager_Administration/index.html++[Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 Logical Volume Manager Administration Guide]_.

Remote Displays::
+
{PRODUCT} and [application]*Anaconda* include VNC (Virtual Network Computing) software to enable remote access to graphical displays. For more information about VNC, see the TigerVNC chapter in the [citetitle]_link:++https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/ch-TigerVNC.html++[Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 System Administrator's Guide]_.

Remote System Access::
+
{PRODUCT} incorporates the OpenSSH suite to provide remote access to the system. The SSH service enables a number of functions, which include access to the command-line from other systems, remote command execution, and network file transfers. During the installation process, [command]`Anaconda` might use the [command]`scp` feature of OpenSSH to transfer crash reports to remote systems. For further details about OpenSSH, see the corresponding section in the link:++https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/index.html++[Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 System Administrator's Guide].

Access Control::
+
SELinux provides Mandatory Access Control (MAC) capabilities that supplement the standard Linux security features. See the [citetitle]_link:++https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/SELinux_Users_and_Administrators_Guide/index.html++[Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 SELinux User's and Administrator's Guide]_ for further information.

Firewall::
+
{PRODUCT} uses [application]*firewalld* to provide firewall features. For further information, see the corresponding chapter in the [citetitle]_link:++https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/sec-Using_Firewalls.html++[Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 SELinux User's and Administrator's Guide]_.

Software Installation::
+
{PRODUCT} uses [command]`yum` to manage the RPM packages that make up the system. See the corresponding chapter in the [citetitle]_link:++https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/part-Installing_and_Managing_Software.html++[Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 Administrator's Guide]_ for further information.

Virtualization::
+
Virtualization provides the capability to simultaneously run multiple operating systems on the same computer. {PRODUCT} also includes tools to install and manage the secondary systems on a {PRODUCT} host. You can select virtualization support during the installation process, or at any time thereafter. See the link:++https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Virtualization_Deployment_and_Administration_Guide/index.html++[Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 Virtualization Deployment and Administration Guide] for more information.
