
:experimental:
include::entities.adoc[]

[[appe-lvm-overview]]
== Understanding LVM

LVM (Logical Volume Management) partitions provide a number of advantages over standard partitions. LVM partitions are formatted as _physical volumes_. One or more physical volumes are combined to form a _volume group_. Each volume group's total storage is then divided into one or more _logical volumes_. The logical volumes function much like standard partitions. They have a file system type, such as `xfs`, and a mount point.

[IMPORTANT]
====

On AMD, Intel, and ARM systems and IBM Power{nbsp}Systems servers, the boot loader cannot read LVM volumes. You must make a standard, non-LVM disk partition for your `/boot` partition.

On IBM System{nbsp}z, the [application]*zipl* boot loader supports `/boot` on LVM logical volumes with linear mapping.

By default, the installation process always creates the `/` and `swap` partitions within LVM volumes, with a separate `/boot` partition on a physical volume.

====

To understand LVM better, imagine the physical volume as a pile of _blocks_. A block is a storage unit used to store data. Several piles of blocks can be combined to make a much larger pile, just as physical volumes are combined to make a volume group. The resulting pile can be subdivided into several smaller piles of arbitrary size, just as a volume group is allocated to several logical volumes.

An administrator can grow or shrink logical volumes without destroying data, unlike standard disk partitions. If the physical volumes in a volume group are on separate drives or RAID arrays, then administrators can also spread a logical volume across the storage devices.

You can lose data if you shrink a logical volume to a smaller capacity than the data on the volume requires. To ensure maximum flexibility, create logical volumes to meet your current needs, and leave excess storage capacity unallocated. You can safely extend logical volumes to use unallocated space, depending on your needs.