
:experimental:
include::entities.adoc[]

[[chap-upgrading-your-current-system]]
== Upgrading Your Current System

The procedure for performing an in-place upgrade on your current system is handled by the following utilities:

* The [application]*Preupgrade Assistant*, which is a diagnostics utility that assesses your current system and identifies potential problems you might encounter during or after the upgrade.

* The [application]*Red{nbsp}Hat Upgrade Tool* utility, which is used to upgrade a system from Red{nbsp}Hat Enterprise{nbsp}Linux version 6 to version 7.

[NOTE]
====

In-place upgrades are currently only supported on AMD64 and Intel{nbsp}64 (`x86_64`) systems. Additionally, only the `Server` variant can be upgraded with [application]*Red{nbsp}Hat Upgrade Tool*.

====

Full documentation covering the process of upgrading from an earlier release of Red{nbsp}Hat Enterprise{nbsp}Linux to Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 is available in the [citetitle]_link:++https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Migration_Planning_Guide/chap-Red_Hat_Enterprise_Linux-Migration_Planning_Guide-Upgrading.html++[Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 Migration Planning Guide]_.

You can also use the link:++https://access.redhat.com/labs/rhelupgradehelper/++[Red{nbsp}Hat Enterprise{nbsp}Linux Upgrade Helper] to guide you through migration from Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}6 to 7.
